-- =============================================================================
-- PPK TEX ERP — Database Schema v1.0
-- Target: PostgreSQL 15+ on Supabase (Mumbai region)
-- Spec source: PPK_TEX_ERP_Master_Spec_v3.0, FabricCosting_FrozenSpec_v1.1,
--              Porvai_Bobbin_ERP_Integration_Spec_v2.1, Module11_Attendance_Addendum_v1.0
--
-- Conventions:
--   * All money columns: NUMERIC(14,4)  -- 4 decimals = paise precision
--   * All percentages: NUMERIC(7,4)     -- 0.0200 = 2%
--   * All weights (kg): NUMERIC(12,4)
--   * All lengths (m):  NUMERIC(12,4)
--   * All counts (Ne):  NUMERIC(8,4)
--   * Timestamps: timestamptz, stored UTC, displayed in Asia/Kolkata
--   * Primary keys: bigint generated by default as identity
--   * Soft delete: status enum 'active' | 'archived' | 'discontinued'
--   * Audit columns: created_at, created_by, updated_at, updated_by on every table
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 0. Extensions & helpers
-- -----------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS "pgcrypto";          -- UUIDs if needed
CREATE EXTENSION IF NOT EXISTS "pg_trgm";           -- fuzzy customer search
CREATE EXTENSION IF NOT EXISTS "btree_gist";        -- exclusion constraints

-- Reusable trigger to keep updated_at fresh
CREATE OR REPLACE FUNCTION fn_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Reusable trigger to capture row history
CREATE OR REPLACE FUNCTION fn_audit_row()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO audit_log(table_name, row_pk, action, old_data, new_data, changed_by)
  VALUES (
    TG_TABLE_NAME,
    COALESCE(NEW.id::text, OLD.id::text),
    TG_OP,
    CASE WHEN TG_OP IN ('UPDATE','DELETE') THEN row_to_json(OLD) ELSE NULL END,
    CASE WHEN TG_OP IN ('INSERT','UPDATE') THEN row_to_json(NEW) ELSE NULL END,
    auth.uid()
  );
  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- -----------------------------------------------------------------------------
-- 1. Enums
-- -----------------------------------------------------------------------------
CREATE TYPE user_role AS ENUM (
  'owner', 'mill_manager', 'sales_manager', 'accounts', 'floor_operator', 'auditor'
);

CREATE TYPE record_status AS ENUM ('active', 'archived', 'discontinued');

CREATE TYPE business_model AS ENUM (
  'inhouse',          -- Model 1: own warp + own loom
  'outsourced',       -- Model 2: own yarn, vendor weaves
  'jobwork',          -- Model 3: customer-owned yarn, you weave
  'resale'            -- Model 4: buy finished fabric, resell
);

CREATE TYPE fabric_type AS ENUM ('woven', 'towel', 'dupatta');
CREATE TYPE production_mode AS ENUM ('inhouse', 'vendor', 'both');
CREATE TYPE yarn_type AS ENUM ('cotton', 'polyester', 'blend');

CREATE TYPE bobbin_location AS ENUM (
  'main_godown',       -- your stock
  'at_vendor',         -- issued to outsourced weaver
  'customer_owned'     -- job work bobbins
);

CREATE TYPE so_status AS ENUM (
  'draft', 'pending_approval', 'approved', 'in_production', 'partial_dispatch',
  'dispatched', 'invoiced', 'paid', 'cancelled'
);

CREATE TYPE invoice_status AS ENUM ('draft', 'issued', 'partial_paid', 'paid', 'overdue', 'cancelled');
CREATE TYPE payment_direction AS ENUM ('in', 'out');

CREATE TYPE shift_code AS ENUM ('morning', 'night');
CREATE TYPE attendance_status AS ENUM ('present', 'absent', 'half_day', 'late', 'early_leave');
CREATE TYPE non_working_reason AS ENUM ('power_cut', 'national_holiday', 'maintenance', 'other');

CREATE TYPE employee_role AS ENUM (
  'weaver', 'fitter', 'folder', 'winder', 'knotter', 'auto', 'office', 'other'
);

CREATE TYPE shift_preference AS ENUM ('morning', 'night', 'either');
CREATE TYPE employee_status AS ENUM ('active', 'inactive', 'resigned');

CREATE TYPE costing_save_path AS ENUM ('quick_quote', 'formal');
CREATE TYPE approval_status AS ENUM ('pending', 'approved', 'rejected');

-- -----------------------------------------------------------------------------
-- 2. Audit log (created first; everything else logs into it)
-- -----------------------------------------------------------------------------
CREATE TABLE audit_log (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_name  text NOT NULL,
  row_pk      text NOT NULL,
  action      text NOT NULL CHECK (action IN ('INSERT','UPDATE','DELETE')),
  old_data    jsonb,
  new_data    jsonb,
  changed_by  uuid,
  changed_at  timestamptz NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_audit_table_row ON audit_log(table_name, row_pk);
CREATE INDEX idx_audit_changed_at ON audit_log(changed_at DESC);

-- -----------------------------------------------------------------------------
-- 3. Company profile & system config (Module 18)
-- -----------------------------------------------------------------------------
CREATE TABLE company_profile (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legal_name      text NOT NULL,
  display_name    text NOT NULL,
  gstin           text NOT NULL CHECK (gstin ~ '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$'),
  pan             text NOT NULL,
  address_line1   text NOT NULL,
  address_line2   text,
  city            text NOT NULL,
  state           text NOT NULL,
  pincode         text NOT NULL,
  phone           text,
  email           text,
  website         text,
  logo_url        text,
  fy_start_month  smallint NOT NULL DEFAULT 4 CHECK (fy_start_month BETWEEN 1 AND 12),
  base_currency   text NOT NULL DEFAULT 'INR',
  created_at      timestamptz NOT NULL DEFAULT NOW(),
  updated_at      timestamptz NOT NULL DEFAULT NOW()
);

-- Single-row guard: only one company profile per database
CREATE UNIQUE INDEX uq_company_profile_singleton ON company_profile((true));

CREATE TABLE system_config (
  key         text PRIMARY KEY,
  value       jsonb NOT NULL,
  description text,
  updated_at  timestamptz NOT NULL DEFAULT NOW(),
  updated_by  uuid
);

COMMENT ON TABLE system_config IS
  'Global config: textile constants 1848/1690/5315, LOOMS overhead breakdown, ' ||
  'document numbering formats, default wastage %, etc.';

-- -----------------------------------------------------------------------------
-- 4. Users & roles (Supabase Auth integration)
-- -----------------------------------------------------------------------------
CREATE TABLE app_user (
  id          uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name   text NOT NULL,
  email       text NOT NULL UNIQUE,
  phone       text,
  role        user_role NOT NULL DEFAULT 'floor_operator',
  status      employee_status NOT NULL DEFAULT 'active',
  last_login  timestamptz,
  created_at  timestamptz NOT NULL DEFAULT NOW(),
  updated_at  timestamptz NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_app_user_updated_at BEFORE UPDATE ON app_user
  FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- -----------------------------------------------------------------------------
-- 5. Master: Customer (Module 15)
-- -----------------------------------------------------------------------------
CREATE TABLE customer (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code                  text NOT NULL UNIQUE,           -- CUST-0001
  name                  text NOT NULL,
  contact_person        text,
  gstin                 text,
  pan                   text,
  phone                 text,
  email                 text,
  whatsapp              text,
  billing_address       text NOT NULL,
  shipping_address      text,
  city                  text,
  state                 text,
  pincode               text,
  payment_terms_days    smallint NOT NULL DEFAULT 30,   -- Net 30, Net 45 etc.
  credit_limit          numeric(14,2) NOT NULL DEFAULT 0,
  is_vip                boolean NOT NULL DEFAULT false,
  notes                 text,
  status                record_status NOT NULL DEFAULT 'active',
  created_at            timestamptz NOT NULL DEFAULT NOW(),
  created_by            uuid REFERENCES app_user(id),
  updated_at            timestamptz NOT NULL DEFAULT NOW(),
  updated_by            uuid REFERENCES app_user(id)
);
CREATE INDEX idx_customer_name_trgm ON customer USING gin (name gin_trgm_ops);
CREATE INDEX idx_customer_status ON customer(status);

CREATE TRIGGER trg_customer_updated_at BEFORE UPDATE ON customer
  FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- -----------------------------------------------------------------------------
-- 6. Master: Mill / Yarn supplier (Module 03)
-- -----------------------------------------------------------------------------
CREATE TABLE mill (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code              text NOT NULL UNIQUE,        -- MILL-001
  name              text NOT NULL,
  contact_person    text,
  gstin             text,
  phone             text,
  email             text,
  address           text,
  city              text,
  state             text,
  is_preferred      boolean NOT NULL DEFAULT false,
  notes             text,
  status            record_status NOT NULL DEFAULT 'active',
  created_at        timestamptz NOT NULL DEFAULT NOW(),
  created_by        uuid REFERENCES app_user(id),
  updated_at        timestamptz NOT NULL DEFAULT NOW(),
  updated_by        uuid REFERENCES app_user(id)
);
CREATE INDEX idx_mill_status ON mill(status);

CREATE TRIGGER trg_mill_updated_at BEFORE UPDATE ON mill
  FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- -----------------------------------------------------------------------------
-- 7. Master: Yarn Count (Module 17) — supports cotton + polyester (Porvai)
-- -----------------------------------------------------------------------------
CREATE TABLE yarn_count (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code            text NOT NULL UNIQUE,           -- C-30, C-150D, etc.
  display_name    text NOT NULL,                  -- "30s combed cotton", "150D Porvai"
  yarn_type       yarn_type NOT NULL DEFAULT 'cotton',

  -- Cotton: user enters Ne directly
  ne              numeric(8,4),                   -- English count

  -- Polyester (Porvai): user enters Denier; NeC auto-computed = 5315 / Denier
  denier          numeric(8,4),

  -- Computed once at insert/update so app code never has to recompute
  -- For polyester: nec_computed = 5315 / denier
  -- For cotton:    nec_computed = ne
  nec_computed    numeric(8,4) GENERATED ALWAYS AS (
    CASE
      WHEN yarn_type = 'polyester' AND denier IS NOT NULL AND denier > 0
        THEN 5315 / denier
      ELSE ne
    END
  ) STORED,

  -- Reference data
  tex             numeric(8,4),                   -- 590.5 / Ne (informational)
  is_doubled      boolean NOT NULL DEFAULT false, -- 2/40s, 2/20s
  is_slub         boolean NOT NULL DEFAULT false, -- 20s slub
  reorder_kg      numeric(12,2) NOT NULL DEFAULT 0,
  notes           text,
  status          record_status NOT NULL DEFAULT 'active',
  created_at      timestamptz NOT NULL DEFAULT NOW(),
  created_by      uuid REFERENCES app_user(id),
  updated_at      timestamptz NOT NULL DEFAULT NOW(),
  updated_by      uuid REFERENCES app_user(id),

  -- If polyester, denier required and ne must be null
  CONSTRAINT chk_polyester_has_denier CHECK (
    (yarn_type = 'polyester' AND denier IS NOT NULL AND ne IS NULL)
    OR
    (yarn_type IN ('cotton','blend') AND ne IS NOT NULL)
  )
);
CREATE INDEX idx_yarn_count_type ON yarn_count(yarn_type);

CREATE TRIGGER trg_yarn_count_updated_at BEFORE UPDATE ON yarn_count
  FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- -----------------------------------------------------------------------------
-- 8. Master: Bobbin (Module 11 + Porvai/Bobbin Spec v2.1)
--    Bobbin = small warp beam, runs parallel to main warp (pavu)
-- -----------------------------------------------------------------------------
CREATE TABLE bobbin (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code                text NOT NULL UNIQUE,            -- BB-72-2000
  description         text NOT NULL,
  ends_per_bobbin     smallint NOT NULL CHECK (ends_per_bobbin > 0),
  bobbin_metre        numeric(10,2) NOT NULL CHECK (bobbin_metre > 0),
  bobbin_price        numeric(12,2) NOT NULL CHECK (bobbin_price >= 0),
  is_lurex            boolean NOT NULL DEFAULT false,  -- decorative second bobbin
  vendor_id           bigint REFERENCES mill(id),      -- supplier (uses mill table)
  reorder_pieces      numeric(8,2) NOT NULL DEFAULT 0,
  loading_per_metre   numeric(10,4) NOT NULL DEFAULT 0.10,  -- handling charge ₹/m
  notes               text,
  status              record_status NOT NULL DEFAULT 'active',
  created_at          timestamptz NOT NULL DEFAULT NOW(),
  created_by          uuid REFERENCES app_user(id),
  updated_at          timestamptz NOT NULL DEFAULT NOW(),
  updated_by          uuid REFERENCES app_user(id)
);

CREATE TRIGGER trg_bobbin_updated_at BEFORE UPDATE ON bobbin
  FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- Bobbin stock (3-location per Porvai+Bobbin Spec v2.1 §1.3)
CREATE TABLE bobbin_stock (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bobbin_id       bigint NOT NULL REFERENCES bobbin(id),
  location        bobbin_location NOT NULL,
  vendor_id       bigint REFERENCES mill(id),         -- if location = at_vendor
  customer_id     bigint REFERENCES customer(id),     -- if location = customer_owned
  quantity_pcs    numeric(10,4) NOT NULL DEFAULT 0,   -- decimal: partial pieces tracked
  updated_at      timestamptz NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_location_party CHECK (
    (location = 'main_godown' AND vendor_id IS NULL AND customer_id IS NULL) OR
    (location = 'at_vendor' AND vendor_id IS NOT NULL AND customer_id IS NULL) OR
    (location = 'customer_owned' AND vendor_id IS NULL AND customer_id IS NOT NULL)
  )
);
CREATE UNIQUE INDEX uq_bobbin_stock_loc ON bobbin_stock(
  bobbin_id, location,
  COALESCE(vendor_id, 0), COALESCE(customer_id, 0)
);

-- -----------------------------------------------------------------------------
-- 9. Master: Vendor (weaving / sizing) — separate from yarn supplier (mill)
-- -----------------------------------------------------------------------------
CREATE TABLE vendor (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code                text NOT NULL UNIQUE,           -- VEN-001
  name                text NOT NULL,
  vendor_type         text NOT NULL CHECK (vendor_type IN ('weaving','sizing','dyeing','folding','other')),
  contact_person      text,
  gstin               text,
  phone               text,
  email               text,
  address             text,
  default_pick_paise  numeric(8,4),                   -- vendor's pick rate
  payment_terms_days  smallint NOT NULL DEFAULT 30,
  notes               text,
  status              record_status NOT NULL DEFAULT 'active',
  created_at          timestamptz NOT NULL DEFAULT NOW(),
  created_by          uuid REFERENCES app_user(id),
  updated_at          timestamptz NOT NULL DEFAULT NOW(),
  updated_by          uuid REFERENCES app_user(id)
);

CREATE TRIGGER trg_vendor_updated_at BEFORE UPDATE ON vendor
  FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- Vendor performance scoreboard (Master Spec v3.0 §2.7)
CREATE TABLE vendor_performance (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendor_id         bigint NOT NULL REFERENCES vendor(id),
  period_start      date NOT NULL,
  period_end        date NOT NULL,
  jobs_total        integer NOT NULL DEFAULT 0,
  jobs_on_time      integer NOT NULL DEFAULT 0,
  metres_promised   numeric(12,2) NOT NULL DEFAULT 0,
  metres_delivered  numeric(12,2) NOT NULL DEFAULT 0,
  variance_pct      numeric(7,4),
  complaints        integer NOT NULL DEFAULT 0,
  on_time_pct       numeric(7,4) GENERATED ALWAYS AS (
    CASE WHEN jobs_total > 0 THEN (jobs_on_time::numeric / jobs_total) * 100 ELSE NULL END
  ) STORED,
  computed_at       timestamptz NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_vendor_perf_vendor ON vendor_performance(vendor_id, period_end DESC);

-- -----------------------------------------------------------------------------
-- 10. Master: Fabric quality / Costing Master (Modules 12, 16)
--     This is the heart of the costing engine.
-- -----------------------------------------------------------------------------
CREATE TABLE costing_master (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quality_code            text NOT NULL UNIQUE,     -- 120HT
  quality_name            text NOT NULL,
  fabric_type             fabric_type NOT NULL,
  production_mode         production_mode NOT NULL,
  status                  record_status NOT NULL DEFAULT 'active',

  -- Warp inputs
  warp_count_id           bigint NOT NULL REFERENCES yarn_count(id),
  warp_ends               integer,                  -- nullable; auto-calc fallback
  tape_length_m           numeric(10,4) NOT NULL,
  shrinkage_pct           numeric(7,4) NOT NULL DEFAULT 0,
  yarn_wastage_pct        numeric(7,4) NOT NULL DEFAULT 0.02,    -- 2%

  -- Weft inputs
  weft_count_id           bigint NOT NULL REFERENCES yarn_count(id),
  pick_ppi                numeric(7,4) NOT NULL,    -- picks per inch
  fabric_length_m         numeric(10,4) NOT NULL,
  weft_allowance_m        numeric(7,4) NOT NULL DEFAULT 2,

  -- Reed / width / selvedge
  reed_count              integer NOT NULL,
  fabric_width_in         numeric(7,4) NOT NULL,
  selvedge_ends           integer NOT NULL DEFAULT 0,

  -- Bobbin block (optional; up to 2)
  use_bobbin_1            boolean NOT NULL DEFAULT false,
  bobbin_1_id             bigint REFERENCES bobbin(id),
  bobbin_1_loading        numeric(10,4) DEFAULT 0.10,
  use_bobbin_2            boolean NOT NULL DEFAULT false,    -- lurex
  bobbin_2_id             bigint REFERENCES bobbin(id),
  bobbin_2_loading        numeric(10,4) DEFAULT 0.10,

  -- Porvai block (towels only)
  use_porvai              boolean NOT NULL DEFAULT false,
  porvai_count_id         bigint REFERENCES yarn_count(id),
  porvai_slevage_length_m numeric(7,4),
  porvai_wastage_pct      numeric(7,4) NOT NULL DEFAULT 0.02,

  -- Cost rate inputs (manual overrides; nullable means use live purchase rate)
  pick_paise_market       numeric(8,4),             -- for Quoted Cost
  vendor_pick_paise       numeric(8,4),             -- for True Cost when outsourced
  sizing_cost_per_m       numeric(10,4) NOT NULL DEFAULT 0,
  auto_cost_per_m         numeric(10,4) NOT NULL DEFAULT 0,
  warp_commission_per_m   numeric(10,4) NOT NULL DEFAULT 0,
  fabric_commission_per_m numeric(10,4) NOT NULL DEFAULT 0,

  -- Provenance & approval
  save_path               costing_save_path NOT NULL DEFAULT 'formal',
  approval_status         approval_status NOT NULL DEFAULT 'pending',
  approved_by             uuid REFERENCES app_user(id),
  approved_at             timestamptz,
  source_so_id            bigint,                   -- if quick_quote, link to SO

  notes                   text,
  created_at              timestamptz NOT NULL DEFAULT NOW(),
  created_by              uuid REFERENCES app_user(id),
  updated_at              timestamptz NOT NULL DEFAULT NOW(),
  updated_by              uuid REFERENCES app_user(id),

  CONSTRAINT chk_porvai_only_for_towel CHECK (
    use_porvai = false OR fabric_type = 'towel'
  ),
  CONSTRAINT chk_porvai_has_count CHECK (
    use_porvai = false OR porvai_count_id IS NOT NULL
  ),
  CONSTRAINT chk_bobbin1_when_used CHECK (
    use_bobbin_1 = false OR bobbin_1_id IS NOT NULL
  ),
  CONSTRAINT chk_bobbin2_when_used CHECK (
    use_bobbin_2 = false OR bobbin_2_id IS NOT NULL
  )
);
CREATE INDEX idx_costing_status ON costing_master(status, approval_status);
CREATE INDEX idx_costing_fabric_type ON costing_master(fabric_type);

CREATE TRIGGER trg_costing_updated_at BEFORE UPDATE ON costing_master
  FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- Customer-specific pricing memory (Master Spec v3.0 §2.7)
CREATE TABLE customer_price_history (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id     bigint NOT NULL REFERENCES customer(id),
  costing_id      bigint NOT NULL REFERENCES costing_master(id),
  price_per_m     numeric(10,4) NOT NULL,
  quoted_at       timestamptz NOT NULL DEFAULT NOW(),
  so_id           bigint
);
CREATE INDEX idx_cust_price_lookup ON customer_price_history(customer_id, costing_id, quoted_at DESC);

-- -----------------------------------------------------------------------------
-- 11. Master: Employee (Module 13 — Attendance Addendum v1.0)
-- -----------------------------------------------------------------------------
CREATE TABLE employee (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code              text NOT NULL UNIQUE,           -- EMP-0001
  full_name         text NOT NULL,
  role              employee_role NOT NULL DEFAULT 'weaver',
  default_shift     shift_preference NOT NULL DEFAULT 'morning',
  date_of_joining   date,
  phone             text,
  id_last4          text,                           -- last 4 of Aadhaar (NOT full)
  status            employee_status NOT NULL DEFAULT 'active',
  notes             text,
  created_at        timestamptz NOT NULL DEFAULT NOW(),
  created_by        uuid REFERENCES app_user(id),
  updated_at        timestamptz NOT NULL DEFAULT NOW(),
  updated_by        uuid REFERENCES app_user(id)
);
CREATE INDEX idx_employee_role ON employee(role);
CREATE INDEX idx_employee_status ON employee(status);

CREATE TRIGGER trg_employee_updated_at BEFORE UPDATE ON employee
  FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- -----------------------------------------------------------------------------
-- 12. Attendance (Module 13)
-- -----------------------------------------------------------------------------
CREATE TABLE attendance_day (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attendance_date date NOT NULL,
  shift           shift_code NOT NULL,
  is_working      boolean NOT NULL DEFAULT true,
  reason          non_working_reason,
  remark          text,
  marked_by       uuid REFERENCES app_user(id),
  marked_at       timestamptz NOT NULL DEFAULT NOW(),
  locked_at       timestamptz,                      -- after 7 days, lock edits

  CONSTRAINT chk_nonworking_has_reason CHECK (
    is_working = true OR reason IS NOT NULL
  )
);
CREATE UNIQUE INDEX uq_attendance_day ON attendance_day(attendance_date, shift);

CREATE TABLE attendance_entry (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attendance_day_id bigint NOT NULL REFERENCES attendance_day(id) ON DELETE CASCADE,
  employee_id     bigint NOT NULL REFERENCES employee(id),
  status          attendance_status NOT NULL,
  remark          text,
  -- Days-worked weight for reports: P/Late/Early=1.0, Half=0.5, Absent=0
  day_weight      numeric(3,2) GENERATED ALWAYS AS (
    CASE status
      WHEN 'present' THEN 1.0
      WHEN 'late' THEN 1.0
      WHEN 'early_leave' THEN 1.0
      WHEN 'half_day' THEN 0.5
      WHEN 'absent' THEN 0.0
    END
  ) STORED,
  marked_by       uuid REFERENCES app_user(id),
  marked_at       timestamptz NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX uq_attendance_entry ON attendance_entry(attendance_day_id, employee_id);
CREATE INDEX idx_attendance_emp ON attendance_entry(employee_id);

-- -----------------------------------------------------------------------------
-- 13. Yarn inventory (Module 09) — lots, stock, weighted-average cost
-- -----------------------------------------------------------------------------
CREATE TABLE yarn_lot (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lot_code          text NOT NULL UNIQUE,           -- LOT-2026-0042
  yarn_count_id     bigint NOT NULL REFERENCES yarn_count(id),
  mill_id           bigint NOT NULL REFERENCES mill(id),
  received_date     date NOT NULL,
  received_kg       numeric(12,4) NOT NULL CHECK (received_kg > 0),
  current_kg        numeric(12,4) NOT NULL,         -- decremented by issues
  cost_per_kg       numeric(12,4) NOT NULL CHECK (cost_per_kg > 0),
  purchase_invoice_id bigint,                       -- FK added later
  notes             text,
  created_at        timestamptz NOT NULL DEFAULT NOW(),
  created_by        uuid REFERENCES app_user(id)
);
CREATE INDEX idx_yarn_lot_count ON yarn_lot(yarn_count_id, received_date DESC);
CREATE INDEX idx_yarn_lot_mill ON yarn_lot(mill_id);

-- View: live weighted-average rate per (mill, count) — used by costing engine
CREATE VIEW v_yarn_weighted_avg AS
SELECT
  yl.mill_id,
  yl.yarn_count_id,
  SUM(yl.current_kg) AS available_kg,
  SUM(yl.current_kg * yl.cost_per_kg) /
    NULLIF(SUM(yl.current_kg), 0) AS weighted_avg_cost
FROM yarn_lot yl
WHERE yl.current_kg > 0
GROUP BY yl.mill_id, yl.yarn_count_id;

-- -----------------------------------------------------------------------------
-- 14. Yarn purchases (Module 10)
-- -----------------------------------------------------------------------------
CREATE TABLE yarn_purchase (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_no          text NOT NULL,                -- vendor's invoice
  internal_no         text NOT NULL UNIQUE,         -- PO-2026-018
  mill_id             bigint NOT NULL REFERENCES mill(id),
  invoice_date        date NOT NULL,
  received_date       date,
  subtotal            numeric(14,2) NOT NULL DEFAULT 0,
  gst_amount          numeric(14,2) NOT NULL DEFAULT 0,
  freight             numeric(14,2) NOT NULL DEFAULT 0,
  total               numeric(14,2) NOT NULL DEFAULT 0,
  payment_status      invoice_status NOT NULL DEFAULT 'issued',
  notes               text,
  created_at          timestamptz NOT NULL DEFAULT NOW(),
  created_by          uuid REFERENCES app_user(id),
  updated_at          timestamptz NOT NULL DEFAULT NOW(),
  updated_by          uuid REFERENCES app_user(id)
);

CREATE TABLE yarn_purchase_line (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_id     bigint NOT NULL REFERENCES yarn_purchase(id) ON DELETE CASCADE,
  yarn_count_id   bigint NOT NULL REFERENCES yarn_count(id),
  lot_id          bigint REFERENCES yarn_lot(id),    -- created on receipt
  quantity_kg     numeric(12,4) NOT NULL CHECK (quantity_kg > 0),
  rate_per_kg     numeric(12,4) NOT NULL CHECK (rate_per_kg > 0),
  amount          numeric(14,2) GENERATED ALWAYS AS (quantity_kg * rate_per_kg) STORED
);

ALTER TABLE yarn_lot
  ADD CONSTRAINT fk_yarn_lot_purchase FOREIGN KEY (purchase_invoice_id)
  REFERENCES yarn_purchase(id);

CREATE TRIGGER trg_yarn_purchase_updated_at BEFORE UPDATE ON yarn_purchase
  FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- -----------------------------------------------------------------------------
-- 15. Sales Order, Quotations, Invoices (Module 04)
-- -----------------------------------------------------------------------------
CREATE TABLE sales_order (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  so_number           text NOT NULL UNIQUE,         -- SO-2026-038
  customer_id         bigint NOT NULL REFERENCES customer(id),
  business_model      business_model NOT NULL,
  order_date          date NOT NULL DEFAULT CURRENT_DATE,
  delivery_date       date,
  status              so_status NOT NULL DEFAULT 'draft',
  subtotal            numeric(14,2) NOT NULL DEFAULT 0,
  gst_amount          numeric(14,2) NOT NULL DEFAULT 0,
  total               numeric(14,2) NOT NULL DEFAULT 0,
  notes               text,
  approved_by         uuid REFERENCES app_user(id),
  approved_at         timestamptz,
  created_at          timestamptz NOT NULL DEFAULT NOW(),
  created_by          uuid REFERENCES app_user(id),
  updated_at          timestamptz NOT NULL DEFAULT NOW(),
  updated_by          uuid REFERENCES app_user(id)
);
CREATE INDEX idx_so_customer ON sales_order(customer_id);
CREATE INDEX idx_so_status ON sales_order(status);

CREATE TABLE sales_order_line (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  so_id           bigint NOT NULL REFERENCES sales_order(id) ON DELETE CASCADE,
  costing_id      bigint NOT NULL REFERENCES costing_master(id),
  quantity_m      numeric(12,2) NOT NULL CHECK (quantity_m > 0),
  rate_per_m      numeric(10,4) NOT NULL CHECK (rate_per_m > 0),
  amount          numeric(14,2) GENERATED ALWAYS AS (quantity_m * rate_per_m) STORED,
  delivered_m     numeric(12,2) NOT NULL DEFAULT 0,
  notes           text
);

ALTER TABLE costing_master
  ADD CONSTRAINT fk_costing_source_so FOREIGN KEY (source_so_id)
  REFERENCES sales_order(id);

ALTER TABLE customer_price_history
  ADD CONSTRAINT fk_cph_so FOREIGN KEY (so_id) REFERENCES sales_order(id);

CREATE TRIGGER trg_so_updated_at BEFORE UPDATE ON sales_order
  FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- Invoice
CREATE TABLE invoice (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_no      text NOT NULL UNIQUE,             -- INV/26-27/0142
  so_id           bigint REFERENCES sales_order(id),
  customer_id     bigint NOT NULL REFERENCES customer(id),
  invoice_date    date NOT NULL DEFAULT CURRENT_DATE,
  due_date        date,
  subtotal        numeric(14,2) NOT NULL DEFAULT 0,
  gst_amount      numeric(14,2) NOT NULL DEFAULT 0,
  total           numeric(14,2) NOT NULL DEFAULT 0,
  amount_paid     numeric(14,2) NOT NULL DEFAULT 0,
  balance         numeric(14,2) GENERATED ALWAYS AS (total - amount_paid) STORED,
  status          invoice_status NOT NULL DEFAULT 'issued',
  pdf_url         text,
  notes           text,
  created_at      timestamptz NOT NULL DEFAULT NOW(),
  created_by      uuid REFERENCES app_user(id),
  updated_at      timestamptz NOT NULL DEFAULT NOW(),
  updated_by      uuid REFERENCES app_user(id)
);
CREATE INDEX idx_invoice_customer ON invoice(customer_id);
CREATE INDEX idx_invoice_due ON invoice(due_date) WHERE status NOT IN ('paid','cancelled');

CREATE TABLE invoice_line (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id      bigint NOT NULL REFERENCES invoice(id) ON DELETE CASCADE,
  costing_id      bigint REFERENCES costing_master(id),
  description     text NOT NULL,
  quantity_m      numeric(12,2) NOT NULL,
  rate_per_m      numeric(10,4) NOT NULL,
  amount          numeric(14,2) GENERATED ALWAYS AS (quantity_m * rate_per_m) STORED
);

CREATE TRIGGER trg_invoice_updated_at BEFORE UPDATE ON invoice
  FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- -----------------------------------------------------------------------------
-- 16. Production batch (Module 05) — in-house weaving
-- -----------------------------------------------------------------------------
CREATE TABLE loom (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loom_code       text NOT NULL UNIQUE,             -- L-01..L-32
  loom_type       text NOT NULL,                    -- 'auto', 'powerloom', 'rapier'
  width_in        numeric(7,2),
  status          text NOT NULL DEFAULT 'running' CHECK (status IN ('running','idle','maintenance','breakdown')),
  notes           text
);

CREATE TABLE production_batch (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_code          text NOT NULL UNIQUE,
  so_line_id          bigint REFERENCES sales_order_line(id),
  costing_id          bigint NOT NULL REFERENCES costing_master(id),
  loom_id             bigint REFERENCES loom(id),
  warp_lot_id         bigint REFERENCES yarn_lot(id),
  weft_lot_id         bigint REFERENCES yarn_lot(id),
  porvai_lot_id       bigint REFERENCES yarn_lot(id),
  bobbin_1_id         bigint REFERENCES bobbin(id),
  bobbin_2_id         bigint REFERENCES bobbin(id),
  pavu_assign_id      bigint REFERENCES pavu_assign(id),  -- CORR-T4: trace to sizing_job
  start_date          date,
  end_date            date,
  produced_m          numeric(12,2) NOT NULL DEFAULT 0,
  rejected_m          numeric(12,2) NOT NULL DEFAULT 0,
  -- Frozen actual costs (for stock valuation - weighted avg of batch costs)
  actual_warp_cost_per_m  numeric(10,4),
  actual_weft_cost_per_m  numeric(10,4),
  actual_pick_cost_per_m  numeric(10,4),
  actual_bobbin_cost_per_m numeric(10,4),
  actual_porvai_cost_per_m numeric(10,4),
  actual_overhead_per_m   numeric(10,4),            -- LOOMS overhead snapshot
  actual_sizing_cost_per_m numeric(10,4),           -- planned sizing ₹/m (CORR-T3)
  actual_sizing_rate_per_kg numeric(10,4),          -- snapshot sizing ₹/kg (CORR-T4)
  actual_true_cost_per_m  numeric(10,4),            -- frozen at batch close
  notes               text,
  created_at          timestamptz NOT NULL DEFAULT NOW(),
  created_by          uuid REFERENCES app_user(id),
  updated_at          timestamptz NOT NULL DEFAULT NOW(),
  updated_by          uuid REFERENCES app_user(id)
);
CREATE INDEX idx_batch_costing ON production_batch(costing_id);
CREATE INDEX idx_batch_warp_lot ON production_batch(warp_lot_id);

CREATE TRIGGER trg_batch_updated_at BEFORE UPDATE ON production_batch
  FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- -----------------------------------------------------------------------------
-- 17. Outsourced weaving (Module 06)
-- -----------------------------------------------------------------------------
CREATE TABLE outsource_order (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ow_number           text NOT NULL UNIQUE,         -- OW-2026-012
  vendor_id           bigint NOT NULL REFERENCES vendor(id),
  so_line_id          bigint REFERENCES sales_order_line(id),
  costing_id          bigint NOT NULL REFERENCES costing_master(id),
  warp_lot_id         bigint REFERENCES yarn_lot(id),
  weft_lot_id         bigint REFERENCES yarn_lot(id),
  porvai_lot_id       bigint REFERENCES yarn_lot(id),
  bobbin_1_id         bigint REFERENCES bobbin(id),
  bobbin_1_pcs_issued numeric(8,2) NOT NULL DEFAULT 0,
  expected_metres     numeric(12,2) NOT NULL,
  pick_paise_agreed   numeric(8,4) NOT NULL,
  issued_date         date NOT NULL,
  promised_date       date,
  delivered_metres    numeric(12,2) NOT NULL DEFAULT 0,
  delivered_date      date,
  bobbin_pcs_returned numeric(10,4) NOT NULL DEFAULT 0,
  status              text NOT NULL DEFAULT 'open' CHECK (status IN ('open','partial','complete','cancelled')),
  notes               text,
  created_at          timestamptz NOT NULL DEFAULT NOW(),
  created_by          uuid REFERENCES app_user(id),
  updated_at          timestamptz NOT NULL DEFAULT NOW(),
  updated_by          uuid REFERENCES app_user(id)
);

CREATE TRIGGER trg_ow_updated_at BEFORE UPDATE ON outsource_order
  FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- -----------------------------------------------------------------------------
-- 18. Job work received (Module 07) — customer brings yarn, you weave
-- -----------------------------------------------------------------------------
CREATE TABLE jobwork_order (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  jw_number           text NOT NULL UNIQUE,         -- JW-2026-024
  customer_id         bigint NOT NULL REFERENCES customer(id),
  costing_id          bigint NOT NULL REFERENCES costing_master(id),
  warp_kg_received    numeric(12,4) NOT NULL DEFAULT 0,
  weft_kg_received    numeric(12,4) NOT NULL DEFAULT 0,
  porvai_kg_received  numeric(12,4) NOT NULL DEFAULT 0,
  bobbin_pcs_received numeric(10,4) NOT NULL DEFAULT 0,
  expected_metres     numeric(12,2) NOT NULL,
  labour_rate_per_m   numeric(10,4) NOT NULL,       -- you only charge labour
  received_date       date NOT NULL,
  promised_date       date,
  delivered_metres    numeric(12,2) NOT NULL DEFAULT 0,
  delivered_date      date,
  status              text NOT NULL DEFAULT 'open' CHECK (status IN ('open','partial','complete','cancelled')),
  notes               text,
  created_at          timestamptz NOT NULL DEFAULT NOW(),
  created_by          uuid REFERENCES app_user(id),
  updated_at          timestamptz NOT NULL DEFAULT NOW(),
  updated_by          uuid REFERENCES app_user(id)
);

CREATE TRIGGER trg_jw_updated_at BEFORE UPDATE ON jobwork_order
  FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- -----------------------------------------------------------------------------
-- 19. Resale fabric (Module 08) — buy finished, resell as-is
-- -----------------------------------------------------------------------------
CREATE TABLE resale_lot (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rl_number           text NOT NULL UNIQUE,         -- RL-2026-008
  vendor_id           bigint NOT NULL REFERENCES vendor(id),
  costing_id          bigint REFERENCES costing_master(id),
  description         text,
  metres_purchased    numeric(12,2) NOT NULL,
  cost_per_m          numeric(10,4) NOT NULL,
  metres_remaining    numeric(12,2) NOT NULL,
  received_date       date NOT NULL,
  notes               text,
  created_at          timestamptz NOT NULL DEFAULT NOW(),
  created_by          uuid REFERENCES app_user(id)
);

-- -----------------------------------------------------------------------------
-- 20. Finished fabric stock (after production / receipt)
-- -----------------------------------------------------------------------------
CREATE TABLE fabric_stock (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  costing_id          bigint NOT NULL REFERENCES costing_master(id),
  source_type         text NOT NULL CHECK (source_type IN ('inhouse','outsourced','jobwork','resale')),
  batch_id            bigint REFERENCES production_batch(id),
  ow_id               bigint REFERENCES outsource_order(id),
  jw_id               bigint REFERENCES jobwork_order(id),
  resale_lot_id       bigint REFERENCES resale_lot(id),
  metres_in           numeric(12,2) NOT NULL,
  metres_out          numeric(12,2) NOT NULL DEFAULT 0,
  metres_available    numeric(12,2) GENERATED ALWAYS AS (metres_in - metres_out) STORED,
  cost_per_m_frozen   numeric(10,4) NOT NULL,        -- True Cost at receipt time
  received_at         timestamptz NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_fabric_stock_costing ON fabric_stock(costing_id);
CREATE INDEX idx_fabric_stock_avail ON fabric_stock(metres_available) WHERE metres_available > 0;

-- -----------------------------------------------------------------------------
-- 21. Payments (Module 09 / Accounts)
-- -----------------------------------------------------------------------------
CREATE TABLE payment (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_no      text NOT NULL UNIQUE,             -- PAY-2026-0142
  direction       payment_direction NOT NULL,
  customer_id     bigint REFERENCES customer(id),
  vendor_id       bigint REFERENCES vendor(id),
  mill_id         bigint REFERENCES mill(id),
  invoice_id      bigint REFERENCES invoice(id),
  purchase_id     bigint REFERENCES yarn_purchase(id),
  amount          numeric(14,2) NOT NULL CHECK (amount > 0),
  payment_date    date NOT NULL DEFAULT CURRENT_DATE,
  mode            text NOT NULL CHECK (mode IN ('cash','upi','neft','rtgs','cheque','card','adjustment')),
  reference       text,                             -- UTR / cheque no
  notes           text,
  created_at      timestamptz NOT NULL DEFAULT NOW(),
  created_by      uuid REFERENCES app_user(id),

  CONSTRAINT chk_payment_party CHECK (
    (direction = 'in' AND customer_id IS NOT NULL) OR
    (direction = 'out' AND (vendor_id IS NOT NULL OR mill_id IS NOT NULL))
  )
);
CREATE INDEX idx_payment_customer ON payment(customer_id);
CREATE INDEX idx_payment_invoice ON payment(invoice_id);

-- -----------------------------------------------------------------------------
-- 22. Document numbering registry (Module 18)
-- -----------------------------------------------------------------------------
CREATE TABLE doc_sequence (
  doc_type        text PRIMARY KEY,                 -- 'so', 'invoice', 'po', 'jw', 'ow', 'rl', 'pay'
  prefix          text NOT NULL,                    -- 'SO', 'INV', 'PO', 'JW'
  format          text NOT NULL,                    -- e.g. '{prefix}-{fy}-{seq:0000}'
  fy_code         text NOT NULL,                    -- '2026', '26-27'
  next_value      bigint NOT NULL DEFAULT 1,
  reset_yearly    boolean NOT NULL DEFAULT true,
  updated_at      timestamptz NOT NULL DEFAULT NOW()
);

-- Function to atomically allocate next document number
CREATE OR REPLACE FUNCTION fn_next_doc_no(p_doc_type text)
RETURNS text AS $$
DECLARE
  v_row doc_sequence%ROWTYPE;
  v_seq text;
BEGIN
  UPDATE doc_sequence
    SET next_value = next_value + 1, updated_at = NOW()
    WHERE doc_type = p_doc_type
    RETURNING * INTO v_row;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Unknown doc_type %', p_doc_type;
  END IF;
  -- Format: PREFIX-FY-SEQ padded to 4
  v_seq := LPAD((v_row.next_value - 1)::text, 4, '0');
  RETURN v_row.prefix || '-' || v_row.fy_code || '-' || v_seq;
END;
$$ LANGUAGE plpgsql;

-- -----------------------------------------------------------------------------
-- 23. Notifications, scheduled exports, integrations (Module 18)
-- -----------------------------------------------------------------------------
CREATE TABLE notification (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         uuid NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
  title           text NOT NULL,
  body            text,
  link            text,
  category        text,                             -- 'low_stock', 'overdue', 'approval', 'system'
  is_read         boolean NOT NULL DEFAULT false,
  created_at      timestamptz NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_notif_user_unread ON notification(user_id) WHERE is_read = false;

CREATE TABLE report_export (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_key      text NOT NULL,                    -- 'sales_summary', 'p_l', etc.
  format          text NOT NULL CHECK (format IN ('pdf','xlsx','csv','png')),
  params          jsonb NOT NULL DEFAULT '{}'::jsonb,
  file_url        text,
  status          text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','running','done','failed')),
  scheduled_for   timestamptz,
  generated_at    timestamptz,
  generated_by    uuid REFERENCES app_user(id)
);

-- =============================================================================
-- VIEWS — the business-logic layer
-- =============================================================================

-- LOOMS overhead breakdown (read from system_config)
CREATE OR REPLACE VIEW v_looms_overhead AS
SELECT
  (value->>'power')::numeric(8,4)        AS power_per_m,
  (value->>'labour')::numeric(8,4)       AS labour_per_m,
  (value->>'maintenance')::numeric(8,4)  AS maintenance_per_m,
  (value->>'depreciation')::numeric(8,4) AS depreciation_per_m,
  (value->>'insurance')::numeric(8,4)    AS insurance_per_m,
  (
    (value->>'power')::numeric +
    (value->>'labour')::numeric +
    (value->>'maintenance')::numeric +
    (value->>'depreciation')::numeric +
    (value->>'insurance')::numeric
  )::numeric(8,4) AS total_per_m
FROM system_config WHERE key = 'looms_overhead_breakdown';

-- Costing computed view: every quality with both Quoted Cost and True Cost
-- Implements Sections 3-5 of FabricCosting_FrozenSpec_v1.1
CREATE OR REPLACE VIEW v_costing_computed AS
WITH overhead AS (SELECT total_per_m FROM v_looms_overhead),
warp_rate AS (
  SELECT cm.id AS costing_id, COALESCE(wa.weighted_avg_cost, 0) AS rate
  FROM costing_master cm
  LEFT JOIN v_yarn_weighted_avg wa ON wa.yarn_count_id = cm.warp_count_id
),
weft_rate AS (
  SELECT cm.id AS costing_id, COALESCE(wa.weighted_avg_cost, 0) AS rate
  FROM costing_master cm
  LEFT JOIN v_yarn_weighted_avg wa ON wa.yarn_count_id = cm.weft_count_id
),
porvai_rate AS (
  SELECT cm.id AS costing_id, COALESCE(wa.weighted_avg_cost, 0) AS rate
  FROM costing_master cm
  LEFT JOIN v_yarn_weighted_avg wa ON wa.yarn_count_id = cm.porvai_count_id
)
SELECT
  cm.id, cm.quality_code, cm.quality_name, cm.fabric_type, cm.production_mode,
  cm.use_porvai, cm.use_bobbin_1, cm.use_bobbin_2,
  -- Yarn Ne values
  wc.nec_computed AS warp_ne,
  ftc.nec_computed AS weft_ne,
  pc.nec_computed AS porvai_ne,
  -- Live yarn rates
  wr.rate AS warp_rate_per_kg,
  ftr.rate AS weft_rate_per_kg,
  pr.rate AS porvai_rate_per_kg,
  -- Metre per gram (Block 1 — woven fabric formulas)
  -- Warp: 1848 / (Ne × Reed × Width × (1 + Shrinkage%))
  CASE WHEN cm.fabric_type IN ('woven','dupatta') AND wc.nec_computed > 0 AND cm.reed_count > 0 AND cm.fabric_width_in > 0
    THEN 1848.0 / (wc.nec_computed * cm.reed_count * cm.fabric_width_in * (1 + cm.shrinkage_pct))
    ELSE NULL END AS warp_metres_per_gram,
  -- Weft: 1690 / (Ne × Pick × Width)  (towel uses fabric length)
  CASE WHEN ftc.nec_computed > 0 AND cm.pick_ppi > 0 AND cm.fabric_width_in > 0
    THEN 1690.0 / (ftc.nec_computed * cm.pick_ppi * cm.fabric_width_in)
    ELSE NULL END AS weft_metres_per_gram,
  -- Porvai weft per metre (Section 2.6): (1690 × NeC / Pick) / (SlevageLength + 3)
  CASE WHEN cm.use_porvai AND pc.nec_computed > 0 AND cm.pick_ppi > 0 AND cm.porvai_slevage_length_m IS NOT NULL
    THEN (1690.0 * pc.nec_computed / cm.pick_ppi) / (cm.porvai_slevage_length_m + 3)
    ELSE 0 END AS porvai_metres_per_gram,
  -- Per-metre yarn costs (₹/m) = (Rate × (1 + Wastage%)) / MetresPerGram / 1000
  -- (1000 because metres-per-gram → metres-per-kg = ×1000)
  CASE WHEN ftc.nec_computed IS NOT NULL THEN
    (wr.rate * (1 + cm.yarn_wastage_pct)) /
      NULLIF((1848.0 / (wc.nec_computed * cm.reed_count * cm.fabric_width_in * (1 + cm.shrinkage_pct))) * 1000, 0)
    ELSE 0 END AS warp_cost_per_m,
  CASE WHEN ftc.nec_computed IS NOT NULL THEN
    (ftr.rate * (1 + cm.yarn_wastage_pct)) /
      NULLIF((1690.0 / (ftc.nec_computed * cm.pick_ppi * cm.fabric_width_in)) * 1000, 0)
    ELSE 0 END AS weft_cost_per_m,
  CASE WHEN cm.use_porvai AND pc.nec_computed IS NOT NULL THEN
    (pr.rate * (1 + cm.porvai_wastage_pct)) /
      NULLIF(((1690.0 * pc.nec_computed / cm.pick_ppi) / (cm.porvai_slevage_length_m + 3)) * 1000, 0)
    ELSE 0 END AS porvai_cost_per_m,
  -- Bobbin cost per metre (Section 2.5): (BobbinPrice / BobbinMetre) + Loading
  CASE WHEN cm.use_bobbin_1 AND b1.bobbin_metre > 0 THEN
    (b1.bobbin_price / b1.bobbin_metre) + COALESCE(cm.bobbin_1_loading, 0)
    ELSE 0 END AS bobbin_1_cost_per_m,
  CASE WHEN cm.use_bobbin_2 AND b2.bobbin_metre > 0 THEN
    (b2.bobbin_price / b2.bobbin_metre) + COALESCE(cm.bobbin_2_loading, 0)
    ELSE 0 END AS bobbin_2_cost_per_m,
  -- Pick cost (paise → ₹/m): pick_paise × pick_ppi × width / 100
  CASE WHEN cm.pick_paise_market IS NOT NULL THEN
    (cm.pick_paise_market * cm.pick_ppi * cm.fabric_width_in) / 100
    ELSE 0 END AS pick_cost_quoted_per_m,
  CASE WHEN cm.production_mode = 'inhouse' THEN
    (SELECT total_per_m FROM v_looms_overhead)
  WHEN cm.vendor_pick_paise IS NOT NULL THEN
    (cm.vendor_pick_paise * cm.pick_ppi * cm.fabric_width_in) / 100
  ELSE 0 END AS pick_or_overhead_true_per_m,
  -- Other commissions
  cm.sizing_cost_per_m, cm.auto_cost_per_m,
  cm.warp_commission_per_m, cm.fabric_commission_per_m
FROM costing_master cm
LEFT JOIN yarn_count wc  ON wc.id = cm.warp_count_id
LEFT JOIN yarn_count ftc ON ftc.id = cm.weft_count_id
LEFT JOIN yarn_count pc  ON pc.id = cm.porvai_count_id
LEFT JOIN bobbin b1      ON b1.id = cm.bobbin_1_id
LEFT JOIN bobbin b2      ON b2.id = cm.bobbin_2_id
LEFT JOIN warp_rate wr   ON wr.costing_id = cm.id
LEFT JOIN weft_rate ftr  ON ftr.costing_id = cm.id
LEFT JOIN porvai_rate pr ON pr.costing_id = cm.id;

-- Final two-cost view used by every quotation / report
CREATE OR REPLACE VIEW v_costing_two_cost AS
SELECT
  c.*,
  (warp_cost_per_m + weft_cost_per_m + porvai_cost_per_m
   + bobbin_1_cost_per_m + bobbin_2_cost_per_m
   + pick_cost_quoted_per_m
   + sizing_cost_per_m + auto_cost_per_m
   + warp_commission_per_m + fabric_commission_per_m)::numeric(10,4) AS quoted_cost_per_m,
  (warp_cost_per_m + weft_cost_per_m + porvai_cost_per_m
   + bobbin_1_cost_per_m + bobbin_2_cost_per_m
   + pick_or_overhead_true_per_m
   + sizing_cost_per_m + auto_cost_per_m
   + warp_commission_per_m + fabric_commission_per_m)::numeric(10,4) AS true_cost_per_m
FROM v_costing_computed c;

-- Customer outstanding balance
CREATE OR REPLACE VIEW v_customer_outstanding AS
SELECT
  c.id AS customer_id, c.code, c.name,
  COALESCE(SUM(i.balance) FILTER (WHERE i.status NOT IN ('paid','cancelled')), 0) AS outstanding,
  COALESCE(SUM(i.balance) FILTER (WHERE i.status NOT IN ('paid','cancelled') AND i.due_date < CURRENT_DATE), 0) AS overdue,
  MAX(i.invoice_date) AS last_invoice_date
FROM customer c
LEFT JOIN invoice i ON i.customer_id = c.id
GROUP BY c.id, c.code, c.name;

-- Days-of-cover per yarn count (reorder forecasting — Master Spec v3.0 §2.7)
CREATE OR REPLACE VIEW v_yarn_days_of_cover AS
WITH consumption_30d AS (
  SELECT
    pb.warp_lot_id AS lot_id,
    SUM(pb.produced_m * COALESCE(c.warp_cost_per_m / NULLIF(yl.cost_per_kg,0), 0)) AS kg_consumed
  FROM production_batch pb
  JOIN yarn_lot yl ON yl.id = pb.warp_lot_id
  LEFT JOIN v_costing_computed c ON c.id = pb.costing_id
  WHERE pb.start_date >= CURRENT_DATE - 30
  GROUP BY pb.warp_lot_id
)
SELECT
  yc.id AS yarn_count_id,
  yc.code,
  yc.display_name,
  COALESCE(SUM(yl.current_kg), 0) AS available_kg,
  COALESCE(SUM(c30.kg_consumed), 0) AS kg_30d,
  CASE WHEN COALESCE(SUM(c30.kg_consumed), 0) > 0
    THEN (COALESCE(SUM(yl.current_kg), 0) / (COALESCE(SUM(c30.kg_consumed), 0) / 30))::numeric(10,2)
    ELSE NULL END AS days_of_cover
FROM yarn_count yc
LEFT JOIN yarn_lot yl ON yl.yarn_count_id = yc.id AND yl.current_kg > 0
LEFT JOIN consumption_30d c30 ON c30.lot_id = yl.id
GROUP BY yc.id, yc.code, yc.display_name;

-- =============================================================================
-- AUDIT TRIGGERS — attach to every business-critical table
-- =============================================================================
CREATE TRIGGER trg_audit_costing AFTER INSERT OR UPDATE OR DELETE ON costing_master
  FOR EACH ROW EXECUTE FUNCTION fn_audit_row();
CREATE TRIGGER trg_audit_so AFTER INSERT OR UPDATE OR DELETE ON sales_order
  FOR EACH ROW EXECUTE FUNCTION fn_audit_row();
CREATE TRIGGER trg_audit_invoice AFTER INSERT OR UPDATE OR DELETE ON invoice
  FOR EACH ROW EXECUTE FUNCTION fn_audit_row();
CREATE TRIGGER trg_audit_payment AFTER INSERT OR UPDATE OR DELETE ON payment
  FOR EACH ROW EXECUTE FUNCTION fn_audit_row();
CREATE TRIGGER trg_audit_customer AFTER UPDATE OR DELETE ON customer
  FOR EACH ROW EXECUTE FUNCTION fn_audit_row();
CREATE TRIGGER trg_audit_company AFTER INSERT OR UPDATE OR DELETE ON company_profile
  FOR EACH ROW EXECUTE FUNCTION fn_audit_row();
CREATE TRIGGER trg_audit_config AFTER INSERT OR UPDATE OR DELETE ON system_config
  FOR EACH ROW EXECUTE FUNCTION fn_audit_row();

-- =============================================================================
-- END schema.sql — run rls.sql next, then seed.sql
-- =============================================================================
