-- ============================================================================
-- Migration 001 — Sizing & Pavu modules  (REDESIGNED)
--
-- Built around the real Shri Nithiya Sizing Mill job-card report:
--   • One sizing_job header per SET NO (vendor's reference) from the report.
--   • One pavu row per physical beam (a single job can have many beams,
--     each with its own beam_no, ends and metres).
--   • pavu_assign tracks which beam goes on which loom — only used for
--     in-house production.  Outsourced beams skip pavu_assign and just sit
--     in the outsource module.
--
-- Fields deliberately omitted per owner's instructions:
--   • Mark column        — vendor's internal unit, ignored on our side.
--   • Gross / Tare / Net — only net consumption is tracked at job level.
--   • Empty beam stock   — out of scope for v0.1.
-- ----------------------------------------------------------------------------
-- Safe to re-run.  Apply via Supabase SQL editor or supabase MCP.
-- ============================================================================

-- ─── ENUM TYPES ─────────────────────────────────────────────────────────────
DO $$ BEGIN
  CREATE TYPE sizing_job_status AS ENUM
    ('draft','sent','in_process','received','assigned','done','cancelled');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE pavu_status AS ENUM
    ('in_stock','on_loom','finished','damaged','scrapped');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE pavu_production_mode AS ENUM ('in_house','outsource');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE pavu_assign_status AS ENUM
    ('queued','mounted','running','completed','removed');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE yarn_source AS ENUM ('purchase_direct','warehouse');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ============================================================================
-- 1. sizing_job  (header — one per vendor SET NO)
-- ============================================================================
CREATE TABLE IF NOT EXISTS sizing_job (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_code              text NOT NULL UNIQUE,                -- SZ-2026-0001 (auto)
  set_no                text,                                -- vendor's "SET NO" (e.g. "994")

  -- Who & what ─────────────────────────────────────────────────────────────
  sizing_vendor_id      bigint NOT NULL REFERENCES vendor(id),  -- vendor_type='sizing'
  yarn_mill_id          bigint NOT NULL REFERENCES mill(id),    -- yarn brand/manufacturer
  warp_count_id         bigint NOT NULL REFERENCES yarn_count(id),
  avg_count             numeric(6,2),                        -- "ends average count" — optional

  -- Yarn source ────────────────────────────────────────────────────────────
  yarn_source           yarn_source NOT NULL DEFAULT 'warehouse',
  yarn_lot_id           bigint REFERENCES yarn_lot(id),      -- set when sourced from warehouse

  -- Quantities ─────────────────────────────────────────────────────────────
  yarn_sent_kg          numeric(12,3) NOT NULL DEFAULT 0,    -- raw warp dispatched to sizing
  yarn_used_kg          numeric(12,3) NOT NULL DEFAULT 0,    -- consumed from this job (balance = sent - used)
  no_of_paavu           smallint NOT NULL DEFAULT 1 CHECK (no_of_paavu > 0),

  -- Billing (optional, for sizing-vendor invoices) ─────────────────────────
  sizing_rate_per_kg    numeric(10,4) NOT NULL DEFAULT 0,
  charges_amount        numeric(12,2) NOT NULL DEFAULT 0,
  gst_pct               numeric(5,2)  NOT NULL DEFAULT 5,
  total_amount          numeric(12,2) NOT NULL DEFAULT 0,

  -- Production plan (set right after job creation) ─────────────────────────
  -- 'in_house' / 'outsource' = applied to ALL beams.
  -- 'mixed'                  = decide per beam on the pavu row.
  default_production_mode pavu_production_mode,
  default_outsource_vendor_id bigint REFERENCES vendor(id),  -- when default mode = outsource

  -- Flow ───────────────────────────────────────────────────────────────────
  status                sizing_job_status NOT NULL DEFAULT 'draft',
  date_sent             date,
  date_received         date,

  notes                 text,
  created_at            timestamptz NOT NULL DEFAULT NOW(),
  created_by            uuid REFERENCES app_user(id),
  updated_at            timestamptz NOT NULL DEFAULT NOW(),
  updated_by            uuid REFERENCES app_user(id),

  CONSTRAINT chk_dates_ordered
    CHECK (date_received IS NULL OR date_sent IS NULL OR date_received >= date_sent),
  CONSTRAINT chk_warehouse_source_has_lot
    CHECK (yarn_source <> 'warehouse' OR yarn_lot_id IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS idx_sizing_vendor  ON sizing_job(sizing_vendor_id, date_sent DESC);
CREATE INDEX IF NOT EXISTS idx_sizing_mill    ON sizing_job(yarn_mill_id);
CREATE INDEX IF NOT EXISTS idx_sizing_count   ON sizing_job(warp_count_id);
CREATE INDEX IF NOT EXISTS idx_sizing_status  ON sizing_job(status);

DROP TRIGGER IF EXISTS trg_sizing_updated_at ON sizing_job;
CREATE TRIGGER trg_sizing_updated_at BEFORE UPDATE ON sizing_job
  FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- ============================================================================
-- 2. pavu  (one row per physical beam)
-- ============================================================================
CREATE TABLE IF NOT EXISTS pavu (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pavu_code             text NOT NULL UNIQUE,                -- PV-2026-00012 (auto)
  sizing_job_id         bigint NOT NULL REFERENCES sizing_job(id) ON DELETE CASCADE,

  beam_no               text NOT NULL,                       -- vendor's beam ref ("5715")
  ends                  integer NOT NULL CHECK (ends > 0),
  meters                numeric(10,2) NOT NULL CHECK (meters > 0),

  -- Where this beam goes ───────────────────────────────────────────────────
  production_mode       pavu_production_mode NOT NULL DEFAULT 'in_house',
  outsource_vendor_id   bigint REFERENCES vendor(id),        -- required if outsource

  status                pavu_status NOT NULL DEFAULT 'in_stock',

  notes                 text,
  created_at            timestamptz NOT NULL DEFAULT NOW(),
  created_by            uuid REFERENCES app_user(id),
  updated_at            timestamptz NOT NULL DEFAULT NOW(),
  updated_by            uuid REFERENCES app_user(id),

  CONSTRAINT uq_pavu_beam_per_job UNIQUE (sizing_job_id, beam_no),
  CONSTRAINT chk_outsource_has_vendor
    CHECK (production_mode <> 'outsource' OR outsource_vendor_id IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS idx_pavu_status  ON pavu(status);
CREATE INDEX IF NOT EXISTS idx_pavu_job     ON pavu(sizing_job_id);
CREATE INDEX IF NOT EXISTS idx_pavu_mode    ON pavu(production_mode);

DROP TRIGGER IF EXISTS trg_pavu_updated_at ON pavu;
CREATE TRIGGER trg_pavu_updated_at BEFORE UPDATE ON pavu
  FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- ============================================================================
-- 3. pavu_assign  (in-house loom mounting record)
-- ============================================================================
CREATE TABLE IF NOT EXISTS pavu_assign (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pavu_id           bigint NOT NULL REFERENCES pavu(id),
  loom_id           bigint NOT NULL REFERENCES loom(id),
  costing_id        bigint REFERENCES costing_master(id),    -- quality being woven

  assigned_date     date NOT NULL DEFAULT CURRENT_DATE,
  start_date        date,
  end_date          date,
  metres_produced   numeric(12,2) NOT NULL DEFAULT 0,

  status            pavu_assign_status NOT NULL DEFAULT 'queued',

  notes             text,
  created_at        timestamptz NOT NULL DEFAULT NOW(),
  created_by        uuid REFERENCES app_user(id),
  updated_at        timestamptz NOT NULL DEFAULT NOW(),
  updated_by        uuid REFERENCES app_user(id),

  CONSTRAINT chk_pa_dates
    CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date)
);

CREATE INDEX IF NOT EXISTS idx_pa_loom    ON pavu_assign(loom_id, status);
CREATE INDEX IF NOT EXISTS idx_pa_pavu    ON pavu_assign(pavu_id);
CREATE INDEX IF NOT EXISTS idx_pa_costing ON pavu_assign(costing_id);

-- One active assignment per loom at a time.
CREATE UNIQUE INDEX IF NOT EXISTS uq_pa_one_active_per_loom
  ON pavu_assign(loom_id)
  WHERE status IN ('queued','mounted','running');

DROP TRIGGER IF EXISTS trg_pa_updated_at ON pavu_assign;
CREATE TRIGGER trg_pa_updated_at BEFORE UPDATE ON pavu_assign
  FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- ============================================================================
-- View — yarn balance per job (sent − used)
-- ============================================================================
CREATE OR REPLACE VIEW v_sizing_job_balance AS
SELECT
  s.id,
  s.job_code,
  s.set_no,
  s.yarn_sent_kg,
  s.yarn_used_kg,
  (s.yarn_sent_kg - s.yarn_used_kg) AS yarn_balance_kg
FROM sizing_job s;

-- ============================================================================
-- ROW LEVEL SECURITY
-- ============================================================================
ALTER TABLE sizing_job   ENABLE ROW LEVEL SECURITY;
ALTER TABLE pavu         ENABLE ROW LEVEL SECURITY;
ALTER TABLE pavu_assign  ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS p_sizing_select  ON sizing_job;
CREATE POLICY p_sizing_select ON sizing_job FOR SELECT
  USING (EXISTS (SELECT 1 FROM app_user u WHERE u.id = auth.uid()));

DROP POLICY IF EXISTS p_pavu_select    ON pavu;
CREATE POLICY p_pavu_select ON pavu FOR SELECT
  USING (EXISTS (SELECT 1 FROM app_user u WHERE u.id = auth.uid()));

DROP POLICY IF EXISTS p_pa_select      ON pavu_assign;
CREATE POLICY p_pa_select ON pavu_assign FOR SELECT
  USING (EXISTS (SELECT 1 FROM app_user u WHERE u.id = auth.uid()));

DROP POLICY IF EXISTS p_sizing_write   ON sizing_job;
CREATE POLICY p_sizing_write ON sizing_job FOR ALL
  USING (EXISTS (
    SELECT 1 FROM app_user u
    WHERE u.id = auth.uid() AND u.role IN ('owner','mill_manager','floor_operator')
  ))
  WITH CHECK (EXISTS (
    SELECT 1 FROM app_user u
    WHERE u.id = auth.uid() AND u.role IN ('owner','mill_manager','floor_operator')
  ));

DROP POLICY IF EXISTS p_pavu_write     ON pavu;
CREATE POLICY p_pavu_write ON pavu FOR ALL
  USING (EXISTS (
    SELECT 1 FROM app_user u
    WHERE u.id = auth.uid() AND u.role IN ('owner','mill_manager','floor_operator')
  ))
  WITH CHECK (EXISTS (
    SELECT 1 FROM app_user u
    WHERE u.id = auth.uid() AND u.role IN ('owner','mill_manager','floor_operator')
  ));

DROP POLICY IF EXISTS p_pa_write       ON pavu_assign;
CREATE POLICY p_pa_write ON pavu_assign FOR ALL
  USING (EXISTS (
    SELECT 1 FROM app_user u
    WHERE u.id = auth.uid() AND u.role IN ('owner','mill_manager','floor_operator')
  ))
  WITH CHECK (EXISTS (
    SELECT 1 FROM app_user u
    WHERE u.id = auth.uid() AND u.role IN ('owner','mill_manager','floor_operator')
  ));

-- ============================================================================
-- AUTO-CODE TRIGGERS  (SZ-YYYY-NNNN / PV-YYYY-NNNNN)
-- ============================================================================
INSERT INTO doc_sequence (prefix, year, next_no, padding)
VALUES ('SZ', EXTRACT(YEAR FROM CURRENT_DATE)::int, 1, 4),
       ('PV', EXTRACT(YEAR FROM CURRENT_DATE)::int, 1, 5)
ON CONFLICT DO NOTHING;

CREATE OR REPLACE FUNCTION fn_sizing_autogen_code() RETURNS trigger AS $$
DECLARE n int; y int;
BEGIN
  IF NEW.job_code IS NULL OR NEW.job_code = '' THEN
    y := EXTRACT(YEAR FROM CURRENT_DATE)::int;
    UPDATE doc_sequence
       SET next_no = next_no + 1
     WHERE prefix = 'SZ' AND year = y
     RETURNING next_no - 1 INTO n;
    IF n IS NULL THEN
      INSERT INTO doc_sequence (prefix, year, next_no, padding)
        VALUES ('SZ', y, 2, 4)
        RETURNING 1 INTO n;
    END IF;
    NEW.job_code := 'SZ-' || y || '-' || LPAD(n::text, 4, '0');
  END IF;
  RETURN NEW;
END $$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_sizing_autogen_code ON sizing_job;
CREATE TRIGGER trg_sizing_autogen_code BEFORE INSERT ON sizing_job
  FOR EACH ROW EXECUTE FUNCTION fn_sizing_autogen_code();

CREATE OR REPLACE FUNCTION fn_pavu_autogen_code() RETURNS trigger AS $$
DECLARE n int; y int;
BEGIN
  IF NEW.pavu_code IS NULL OR NEW.pavu_code = '' THEN
    y := EXTRACT(YEAR FROM CURRENT_DATE)::int;
    UPDATE doc_sequence
       SET next_no = next_no + 1
     WHERE prefix = 'PV' AND year = y
     RETURNING next_no - 1 INTO n;
    IF n IS NULL THEN
      INSERT INTO doc_sequence (prefix, year, next_no, padding)
        VALUES ('PV', y, 2, 5)
        RETURNING 1 INTO n;
    END IF;
    NEW.pavu_code := 'PV-' || y || '-' || LPAD(n::text, 5, '0');
  END IF;
  RETURN NEW;
END $$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_pavu_autogen_code ON pavu;
CREATE TRIGGER trg_pavu_autogen_code BEFORE INSERT ON pavu
  FOR EACH ROW EXECUTE FUNCTION fn_pavu_autogen_code();

-- ============================================================================
-- HOUSEKEEPING — auto-update pavu.status when its assignment changes.
-- ============================================================================
CREATE OR REPLACE FUNCTION fn_pa_sync_pavu_status() RETURNS trigger AS $$
BEGIN
  IF NEW.status IN ('queued','mounted','running') THEN
    UPDATE pavu SET status = 'on_loom'  WHERE id = NEW.pavu_id;
  ELSIF NEW.status IN ('completed','removed') THEN
    UPDATE pavu SET status = 'finished' WHERE id = NEW.pavu_id;
  END IF;
  RETURN NEW;
END $$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_pa_sync_pavu_status ON pavu_assign;
CREATE TRIGGER trg_pa_sync_pavu_status
  AFTER INSERT OR UPDATE OF status ON pavu_assign
  FOR EACH ROW EXECUTE FUNCTION fn_pa_sync_pavu_status();

-- ============================================================================
-- Add destination flag to yarn_lot — so purchase entry can mark stock as
-- delivered directly to a sizing vendor instead of our warehouse.
-- ============================================================================
ALTER TABLE yarn_lot
  ADD COLUMN IF NOT EXISTS delivery_destination text
    NOT NULL DEFAULT 'warehouse'
    CHECK (delivery_destination IN ('warehouse','sizing')),
  ADD COLUMN IF NOT EXISTS sizing_vendor_id bigint REFERENCES vendor(id);

-- End of migration 001 ─────────────────────────────────────────────────────
