-- ─────────────────────────────────────────────────────────────────────────
-- 019_delivery_challan_and_delivery_report.sql        (CORR-R11)
--
-- Two things in one migration:
--
--   1. delivery_challan + dc_line tables
--      ------------------------------------
--      A Delivery Challan (DC) is the document that travels with the goods
--      when fabric/yarn is dispatched. It is NOT a tax invoice — it proves
--      what physically left the godown. One invoice can be delivered in
--      several DCs (split deliveries). These tables are the structure
--      decided in the owner's D11 ruling (Correction Guide §Owner decisions).
--
--      The DC *entry screen* and PDF are a separate card (CORR-R-DC1) — this
--      migration only lays down the tables so the R11 report can read them.
--      DC numbering is therefore left to the entry screen; dc_no is just a
--      UNIQUE text column here.
--
--   2. v_invoice_delivery_status view  (the actual R11 report data)
--      ------------------------------------------------------------
--      One row per sales invoice. Compares the metres billed on the invoice
--      against the metres covered by its issued DCs and classifies each
--      invoice as:
--          missing  - no DC raised yet
--          partial  - some metres delivered, but less than invoiced
--          full     - delivered metres cover the invoiced metres
--          over     - delivered metres exceed invoiced (data-entry warning)
--      A 0.5 m tolerance absorbs rounding between cut lengths.
--
--      Until DCs start being entered, every invoice shows "missing" — that
--      is the correct and useful state (it is a to-do list of undispatched
--      invoices).
--
-- Idempotent: safe to re-run. Wrapped in a single transaction.
-- ─────────────────────────────────────────────────────────────────────────

BEGIN;

-- ===========================================================================
-- 1. delivery_challan  (header — one per physical dispatch)
-- ===========================================================================
CREATE TABLE IF NOT EXISTS delivery_challan (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dc_no             text NOT NULL UNIQUE,                 -- e.g. DC/26-27/009
  dc_date           date NOT NULL DEFAULT CURRENT_DATE,
  copy_type         text NOT NULL DEFAULT 'original'
                      CHECK (copy_type IN ('original','duplicate','triplicate')),

  -- Linkage — exactly one of invoice_id / jobwork_id is set.
  -- jobwork_id has no FK yet: the jobwork table is finalised in a P-card.
  invoice_id        bigint REFERENCES invoice(id),
  jobwork_id        bigint,

  -- Party
  party_kind        text NOT NULL DEFAULT 'customer'
                      CHECK (party_kind IN ('customer','vendor')),
  customer_id       bigint REFERENCES customer(id),
  vendor_id         bigint REFERENCES vendor(id),
  bill_to_name      text NOT NULL,
  bill_to_gstin     text,
  bill_to_address   text,
  ship_to_name      text,
  ship_to_gstin     text,
  ship_to_address   text,
  place_of_supply   text,
  state_code        text,

  -- Goods description (one fabric quality per DC, per the sample DC)
  quality_desc      text,
  agent_name        text,

  -- Delivery details
  vehicle_num       text,
  fabric_quality    text,
  fabric_width      text,
  fabric_pinning_cm numeric(6,2),
  fabric_weight_gsm text,
  total_metres      numeric(12,3) NOT NULL DEFAULT 0,
  total_pieces      integer       NOT NULL DEFAULT 0,
  total_bundles     integer       NOT NULL DEFAULT 0,

  -- Status & audit
  status            text NOT NULL DEFAULT 'issued'
                      CHECK (status IN ('issued','cancelled')),
  notes             text,
  created_at        timestamptz NOT NULL DEFAULT NOW(),
  created_by        uuid REFERENCES app_user(id),
  updated_at        timestamptz NOT NULL DEFAULT NOW(),
  updated_by        uuid REFERENCES app_user(id),

  CONSTRAINT dc_linkage CHECK ((invoice_id IS NOT NULL) <> (jobwork_id IS NOT NULL)),
  CONSTRAINT dc_party CHECK (
    (party_kind = 'customer' AND customer_id IS NOT NULL AND vendor_id IS NULL) OR
    (party_kind = 'vendor'   AND vendor_id   IS NOT NULL AND customer_id IS NULL)
  )
);

CREATE INDEX IF NOT EXISTS idx_dc_invoice  ON delivery_challan(invoice_id);
CREATE INDEX IF NOT EXISTS idx_dc_customer ON delivery_challan(customer_id);
CREATE INDEX IF NOT EXISTS idx_dc_date     ON delivery_challan(dc_date DESC);

DROP TRIGGER IF EXISTS trg_dc_updated_at ON delivery_challan;
CREATE TRIGGER trg_dc_updated_at BEFORE UPDATE ON delivery_challan
  FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- ===========================================================================
-- 2. dc_line  (piece-by-piece quantity grid)
-- ===========================================================================
CREATE TABLE IF NOT EXISTS dc_line (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dc_id       bigint NOT NULL REFERENCES delivery_challan(id) ON DELETE CASCADE,
  piece_no    integer NOT NULL,
  metres      numeric(8,3) NOT NULL DEFAULT 0,
  bundle_no   integer,
  remarks     text,
  CONSTRAINT uq_dc_line_piece UNIQUE (dc_id, piece_no)
);

CREATE INDEX IF NOT EXISTS idx_dc_line_dc ON dc_line(dc_id);

-- ===========================================================================
-- 3. ROW LEVEL SECURITY
--    Read: any logged-in app_user. Write: owner / mill_manager / accounts /
--    sales_manager (the roles that raise dispatch paperwork).
-- ===========================================================================
ALTER TABLE delivery_challan ENABLE ROW LEVEL SECURITY;
ALTER TABLE dc_line          ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS p_dc_select ON delivery_challan;
CREATE POLICY p_dc_select ON delivery_challan FOR SELECT
  USING (EXISTS (SELECT 1 FROM app_user u WHERE u.id = auth.uid()));

DROP POLICY IF EXISTS p_dc_write ON delivery_challan;
CREATE POLICY p_dc_write ON delivery_challan FOR ALL
  USING (EXISTS (
    SELECT 1 FROM app_user u
    WHERE u.id = auth.uid()
      AND u.role IN ('owner','mill_manager','accounts','sales_manager')
  ))
  WITH CHECK (EXISTS (
    SELECT 1 FROM app_user u
    WHERE u.id = auth.uid()
      AND u.role IN ('owner','mill_manager','accounts','sales_manager')
  ));

DROP POLICY IF EXISTS p_dc_line_select ON dc_line;
CREATE POLICY p_dc_line_select ON dc_line FOR SELECT
  USING (EXISTS (SELECT 1 FROM app_user u WHERE u.id = auth.uid()));

DROP POLICY IF EXISTS p_dc_line_write ON dc_line;
CREATE POLICY p_dc_line_write ON dc_line FOR ALL
  USING (EXISTS (
    SELECT 1 FROM app_user u
    WHERE u.id = auth.uid()
      AND u.role IN ('owner','mill_manager','accounts','sales_manager')
  ))
  WITH CHECK (EXISTS (
    SELECT 1 FROM app_user u
    WHERE u.id = auth.uid()
      AND u.role IN ('owner','mill_manager','accounts','sales_manager')
  ));

-- ===========================================================================
-- 4. v_invoice_delivery_status  (CORR-R11 report data)
-- ===========================================================================
DROP VIEW IF EXISTS public.v_invoice_delivery_status CASCADE;

CREATE VIEW public.v_invoice_delivery_status
WITH (security_invoker = on) AS
WITH invoiced AS (
  -- quantity billed on each invoice (sum of its line quantities — metres
  -- for fabric invoices; the dominant case for delivery tracking)
  SELECT invoice_id, COALESCE(SUM(quantity), 0) AS invoiced_m
  FROM invoice_line
  GROUP BY invoice_id
),
delivered AS (
  -- metres covered by issued (non-cancelled) DCs per invoice
  SELECT
    invoice_id,
    COUNT(*)                          AS dc_count,
    COALESCE(SUM(total_metres), 0)    AS delivered_m,
    MAX(dc_date)                      AS last_dc_date
  FROM delivery_challan
  WHERE status = 'issued'
    AND invoice_id IS NOT NULL
  GROUP BY invoice_id
)
SELECT
  i.id                                          AS invoice_id,
  i.invoice_no,
  i.invoice_date,
  i.doc_type,
  i.status                                      AS invoice_status,
  i.customer_id,
  c.code                                        AS customer_code,
  c.name                                        AS customer_name,
  i.total                                       AS invoice_total,

  COALESCE(iv.invoiced_m, 0)::numeric(14,2)      AS invoiced_m,
  COALESCE(d.delivered_m, 0)::numeric(14,2)      AS delivered_m,
  GREATEST(
    COALESCE(iv.invoiced_m, 0) - COALESCE(d.delivered_m, 0),
    0
  )::numeric(14,2)                               AS undelivered_m,
  COALESCE(d.dc_count, 0)::integer               AS dc_count,
  d.last_dc_date,

  CASE
    -- nothing dispatched yet
    WHEN COALESCE(d.dc_count, 0) = 0
      THEN 'missing'
    -- dispatched more than billed — flag for review
    WHEN COALESCE(d.delivered_m, 0) > COALESCE(iv.invoiced_m, 0) + 0.5
      THEN 'over'
    -- dispatch covers the bill (within 0.5 m tolerance)
    WHEN COALESCE(d.delivered_m, 0) >= COALESCE(iv.invoiced_m, 0) - 0.5
      THEN 'full'
    -- something went out, but not the whole order
    ELSE 'partial'
  END                                            AS delivery_status

FROM invoice i
LEFT JOIN customer c  ON c.id = i.customer_id
LEFT JOIN invoiced iv ON iv.invoice_id = i.id
LEFT JOIN delivered d ON d.invoice_id = i.id
-- only customer-facing sales invoices need a DC; credit/debit notes do not
WHERE i.doc_type IN ('tax_invoice','yarn_sale','general_sale')
  AND i.status NOT IN ('draft','cancelled');

COMMENT ON VIEW public.v_invoice_delivery_status IS
  'CORR-R11 Invoice -> DC delivery report. One row per sales invoice with billed metres vs metres covered by issued delivery challans, classified missing / partial / full / over.';

COMMIT;
