-- ─────────────────────────────────────────────────────────────────────────
-- 020_shift_production_log.sql        (foundation for CORR-P4)
--
-- The Loom Utilisation card (CORR-P4) asks for per-loom % uptime and
-- metres-per-shift. The schema had no shift-level production capture, so a
-- true uptime number could not be calculated. This migration adds that
-- capture: one table, production_shift_log.
--
-- One row = one loom, on one date, in one shift (day or night). It records
-- the good metres woven, how many minutes the loom was stopped, why it was
-- stopped, and which weaver ran it.
--
-- The unit runs two 12-hour shifts. 12 hours = 720 minutes; that constant is
-- the denominator for the uptime % the CORR-P4 dashboard view will compute.
-- It is NOT stored on every row — it lives once, in application code.
--
-- "shift" is a plain two-value text column (day / night), not a shift-master
-- table. A full shift master with rosters is a later card (CORR-A2) and must
-- not be built twice.
--
-- Idempotent: safe to re-run. Wrapped in a single transaction.
-- ─────────────────────────────────────────────────────────────────────────

BEGIN;

-- ===========================================================================
-- 1. production_shift_log
-- ===========================================================================
CREATE TABLE IF NOT EXISTS production_shift_log (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  log_date          date NOT NULL DEFAULT CURRENT_DATE,
  shift             text NOT NULL
                      CHECK (shift IN ('day','night')),
  loom_id           bigint NOT NULL REFERENCES loom(id),

  weaver_name       text,

  metres_woven      numeric(14,2) NOT NULL DEFAULT 0
                      CHECK (metres_woven >= 0),
  downtime_minutes  integer NOT NULL DEFAULT 0
                      CHECK (downtime_minutes >= 0 AND downtime_minutes <= 720),
  downtime_reason   text
                      CHECK (downtime_reason IN
                        ('warp_break','no_weft','maintenance','power_cut','other')),

  notes             text,
  created_at        timestamptz NOT NULL DEFAULT NOW(),
  created_by        uuid REFERENCES app_user(id),
  updated_at        timestamptz NOT NULL DEFAULT NOW(),
  updated_by        uuid REFERENCES app_user(id),

  -- A reason is required whenever the loom was stopped, and must be empty
  -- when it was not — keeps the data honest.
  CONSTRAINT psl_reason_when_downtime CHECK (
    (downtime_minutes > 0  AND downtime_reason IS NOT NULL) OR
    (downtime_minutes = 0  AND downtime_reason IS NULL)
  ),

  -- The same loom cannot be logged twice for the same date + shift. This is
  -- also what lets the entry screen safely re-save (upsert) a whole shift.
  CONSTRAINT uq_shift_log_loom UNIQUE (log_date, shift, loom_id)
);

CREATE INDEX IF NOT EXISTS idx_psl_date  ON production_shift_log(log_date DESC);
CREATE INDEX IF NOT EXISTS idx_psl_loom  ON production_shift_log(loom_id);

DROP TRIGGER IF EXISTS trg_psl_updated_at ON production_shift_log;
CREATE TRIGGER trg_psl_updated_at BEFORE UPDATE ON production_shift_log
  FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

COMMENT ON TABLE production_shift_log IS
  'Per-loom, per-shift production capture (day/night). Feeds the CORR-P4 '
  'loom utilisation dashboard. 720 min = one 12-hour shift.';

-- ===========================================================================
-- 2. ROW LEVEL SECURITY
--    Read: any logged-in app_user. Write: owner / mill_manager (the roles
--    responsible for the weaving floor).
-- ===========================================================================
ALTER TABLE production_shift_log ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS p_psl_select ON production_shift_log;
CREATE POLICY p_psl_select ON production_shift_log FOR SELECT
  USING (EXISTS (SELECT 1 FROM app_user u WHERE u.id = auth.uid()));

DROP POLICY IF EXISTS p_psl_write ON production_shift_log;
CREATE POLICY p_psl_write ON production_shift_log FOR ALL
  USING (EXISTS (
    SELECT 1 FROM app_user u
    WHERE u.id = auth.uid()
      AND u.role IN ('owner','mill_manager')
  ))
  WITH CHECK (EXISTS (
    SELECT 1 FROM app_user u
    WHERE u.id = auth.uid()
      AND u.role IN ('owner','mill_manager')
  ));

COMMIT;
