-- ────────────────────────────────────────────────────────────────────────────
-- Migration 031 — Wage entries + pro-rata batch allocation  (CORR-T4)
--
--   Until now the Wages page was a stub and `production_batch.actual_true_cost_per_m`
--   carried only the planned costing (yarn + bobbin + sizing + overhead + pick).
--   It did NOT carry mill labour wages — those were paid weekly/ad-hoc but
--   never spread back across the batches they produced. T4 closes that gap.
--
--   v1 scope:
--     - wage_entry table: one row per payment (advance / weekly settlement /
--       adjustment). Each row has a period window so the allocation knows
--       which batches the payment was earned across.
--     - employee.wage_alloc_basis: per-employee choice of allocation basis
--       (metres produced OR loom-shifts worked). Vendor batches never receive
--       mill wages — they already carry the contractor's pick rate.
--     - v_batch_wage_allocation: line-level view (one row per wage_entry ×
--       batch overlap) showing each batch's share of each wage payment.
--     - v_batch_wage_total: rolled-up to one row per batch with the total
--       allocated wage and ₹/m.
--
--   Decisions (from owner, this session):
--     * Mixed frequency — same table can hold weekly settlements + ad-hoc
--       advances; the `kind` column distinguishes them.
--     * Allocation basis chosen per employee, not globally. Defaults to
--       'metres' (simpler / safer for new staff).
--     * In-house batches only. production_batch.production_mode = 'inhouse'.
--
--   This migration intentionally does NOT modify
--   production_batch.actual_true_cost_per_m. The wage allocation lives in a
--   view so we can iterate the formula without rewriting batch rows. A future
--   migration can fold v_batch_wage_total.wage_per_m into a snapshot column
--   once the formula is stable in production.
--
-- Safe to re-run: every CREATE uses IF NOT EXISTS / OR REPLACE; ALTER TABLE
-- uses ADD COLUMN IF NOT EXISTS.
-- ────────────────────────────────────────────────────────────────────────────

BEGIN;

-- ─── 1. Allocation basis on employee ─────────────────────────────────────
ALTER TABLE employee
  ADD COLUMN IF NOT EXISTS wage_alloc_basis text NOT NULL DEFAULT 'metres';

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'employee_wage_alloc_basis_check'
  ) THEN
    ALTER TABLE employee
      ADD CONSTRAINT employee_wage_alloc_basis_check
      CHECK (wage_alloc_basis IN ('metres','loom_shifts'));
  END IF;
END $$;

COMMENT ON COLUMN employee.wage_alloc_basis IS
  'How this employee''s wages spread across in-house batches: ''metres'' '
  '(proportional to fabric metres produced in the wage period) or '
  '''loom_shifts'' (proportional to loom-shifts the batch occupied on the '
  'employee''s loom). Vendor batches never receive mill wage allocation. CORR-T4.';

-- ─── 2. wage_entry table ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS wage_entry (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id   bigint NOT NULL REFERENCES employee(id),
  pay_date      date NOT NULL,
  period_start  date NOT NULL,
  period_end    date NOT NULL,
  kind          text NOT NULL,
  amount        numeric(12,2) NOT NULL,
  notes         text,
  created_at    timestamptz NOT NULL DEFAULT now(),
  created_by    uuid REFERENCES app_user(id),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  updated_by    uuid REFERENCES app_user(id),
  CONSTRAINT wage_entry_amount_nonneg CHECK (amount >= 0),
  CONSTRAINT wage_entry_kind_check
    CHECK (kind IN ('advance','settlement','adjustment')),
  CONSTRAINT wage_entry_period_order
    CHECK (period_end >= period_start)
);

COMMENT ON TABLE wage_entry IS
  'Wages paid to mill employees. One row per payment. Advances and weekly '
  'settlements live in the same table; the kind column distinguishes them. '
  'The period_start/end window determines which production_batch rows share '
  'this payment via v_batch_wage_allocation. CORR-T4.';

CREATE INDEX IF NOT EXISTS ix_wage_entry_employee_period
  ON wage_entry(employee_id, period_start, period_end);
CREATE INDEX IF NOT EXISTS ix_wage_entry_pay_date
  ON wage_entry(pay_date);

CREATE TRIGGER trg_wage_entry_updated_at
  BEFORE UPDATE ON wage_entry
  FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- ─── 3. RLS — owner + accounts manage; mill_manager + auditor read ──────
ALTER TABLE wage_entry ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS wage_entry_read ON wage_entry;
CREATE POLICY wage_entry_read ON wage_entry
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM app_user u
       WHERE u.id = auth.uid()
         AND u.status = 'active'
         AND u.role IN ('owner','accounts','mill_manager','auditor')
    )
  );

DROP POLICY IF EXISTS wage_entry_write ON wage_entry;
CREATE POLICY wage_entry_write ON wage_entry
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM app_user u
       WHERE u.id = auth.uid()
         AND u.status = 'active'
         AND u.role IN ('owner','accounts')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM app_user u
       WHERE u.id = auth.uid()
         AND u.status = 'active'
         AND u.role IN ('owner','accounts')
    )
  );

-- ─── 4. Line-level allocation view ────────────────────────────────────────
-- For each (wage_entry, batch) where the batch's production window overlaps
-- the wage period, compute that batch's share. Basis comes from the
-- employee. We compute both bases at row level so the allocator can pick.
CREATE OR REPLACE VIEW v_batch_wage_allocation
  WITH (security_invoker = true) AS
WITH
  -- Inhouse batches only. Fall back to created_at::date if window cols are
  -- NULL so a brand-new batch still allocates against today's wages.
  batch_window AS (
    SELECT
      pb.id                                       AS batch_id,
      pb.loom_id,
      pb.produced_m,
      COALESCE(pb.start_date, pb.created_at::date) AS start_date,
      COALESCE(pb.end_date,   pb.created_at::date) AS end_date
    FROM production_batch pb
    JOIN costing_master cm ON cm.id = pb.costing_id
    WHERE cm.production_mode = 'inhouse'
  ),
  -- Loom-shifts each batch occupied: count shift_log rows where the loom
  -- and date intersect the batch window.
  batch_shift_count AS (
    SELECT
      bw.batch_id,
      COUNT(*) AS shift_count
    FROM batch_window bw
    JOIN production_shift_log psl
      ON psl.loom_id = bw.loom_id
     AND psl.log_date BETWEEN bw.start_date AND bw.end_date
    GROUP BY bw.batch_id
  ),
  -- All (wage_entry × batch) overlap pairs.
  pair_overlap AS (  -- renamed from "overlaps" which is a Postgres reserved word
    SELECT
      we.id              AS wage_entry_id,
      we.employee_id,
      we.amount,
      we.period_start,
      we.period_end,
      e.wage_alloc_basis AS basis,
      bw.batch_id,
      bw.produced_m,
      COALESCE(bsc.shift_count, 0) AS shift_count
    FROM wage_entry we
    JOIN employee e        ON e.id = we.employee_id
    JOIN batch_window bw
      ON bw.start_date <= we.period_end
     AND bw.end_date   >= we.period_start
    LEFT JOIN batch_shift_count bsc ON bsc.batch_id = bw.batch_id
  ),
  -- Denominator: total basis across all batches sharing a given wage_entry.
  totals AS (
    SELECT
      wage_entry_id,
      SUM(CASE WHEN basis = 'metres'      THEN COALESCE(produced_m, 0) ELSE 0 END) AS metres_total,
      SUM(CASE WHEN basis = 'loom_shifts' THEN shift_count               ELSE 0 END) AS shifts_total
    FROM pair_overlap
    GROUP BY wage_entry_id
  )
SELECT
  p.batch_id,
  p.wage_entry_id,
  p.employee_id,
  p.basis,
  p.amount AS wage_amount_inr,
  CASE
    WHEN p.basis = 'metres'      AND COALESCE(t.metres_total, 0) > 0
      THEN p.amount * (COALESCE(p.produced_m, 0) / t.metres_total)
    WHEN p.basis = 'loom_shifts' AND COALESCE(t.shifts_total, 0) > 0
      THEN p.amount * (p.shift_count::numeric / t.shifts_total)
    ELSE 0
  END AS allocated_wage_inr
FROM pair_overlap p
LEFT JOIN totals t USING (wage_entry_id);

COMMENT ON VIEW v_batch_wage_allocation IS
  'Line-level pro-rata wage allocation: one row per (wage_entry × batch) '
  'overlap. The allocator chooses metres-based or loom-shifts-based per '
  'employee. Vendor batches are excluded — they carry the contractor pick '
  'rate instead. CORR-T4.';

-- ─── 5. Rolled-up per-batch wage total ────────────────────────────────────
CREATE OR REPLACE VIEW v_batch_wage_total
  WITH (security_invoker = true) AS
SELECT
  pb.id AS batch_id,
  pb.batch_code,
  pb.produced_m,
  COALESCE(SUM(vba.allocated_wage_inr), 0) AS total_wage_inr,
  CASE
    WHEN pb.produced_m > 0
      THEN COALESCE(SUM(vba.allocated_wage_inr), 0) / pb.produced_m
    ELSE 0
  END AS wage_per_m
FROM production_batch pb
LEFT JOIN v_batch_wage_allocation vba ON vba.batch_id = pb.id
GROUP BY pb.id, pb.batch_code, pb.produced_m;

COMMENT ON VIEW v_batch_wage_total IS
  'One row per in-house batch with the total allocated mill wages (₹) and '
  '₹/m. Sums v_batch_wage_allocation. Wages keep arriving after a batch '
  'closes, so this view is reactive and not a stored snapshot. CORR-T4.';

COMMIT;
