-- ────────────────────────────────────────────────────────────────────────────
-- Migration 035 — Cash expense entries + pro-rata batch allocation
--
--   Mill cash outflows that are NOT wages — spares, carpenter, electrical,
--   knotting, auto, office, others. These need to land on the per-batch
--   actual cost the same way wages do, otherwise true cost under-reports.
--
--   Decisions (from owner, this session):
--     * One unified table; the category column distinguishes line types.
--     * Pro-rata by metres across all in-house batches whose production
--       window overlaps period_start..period_end (same algo as wages with
--       basis = 'metres').
--     * No payee table — `title` free-text is the only label.
--     * Vendor batches excluded (they already carry the contractor pick rate).
-- ────────────────────────────────────────────────────────────────────────────

BEGIN;

-- ─── 1. expense_entry table ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS expense_entry (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category      text NOT NULL,
  title         text NOT NULL,
  amount        numeric(12,2) NOT NULL,
  pay_date      date NOT NULL,
  period_start  date NOT NULL,
  period_end    date NOT NULL,
  notes         text,
  created_at    timestamptz NOT NULL DEFAULT now(),
  created_by    uuid REFERENCES app_user(id),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  updated_by    uuid REFERENCES app_user(id),
  CONSTRAINT expense_entry_amount_nonneg CHECK (amount >= 0),
  CONSTRAINT expense_entry_category_check
    CHECK (category IN ('spares','carpenter','electrical','knotting','auto','office','others')),
  CONSTRAINT expense_entry_period_order CHECK (period_end >= period_start)
);

COMMENT ON TABLE expense_entry IS
  'Mill cash expenses other than wages — spares, carpenter, electrical, '
  'knotting, auto, office, others. Allocated pro-rata by metres across '
  'in-house batches whose production overlaps period_start..period_end.';

CREATE INDEX IF NOT EXISTS ix_expense_entry_category_period
  ON expense_entry(category, period_start, period_end);
CREATE INDEX IF NOT EXISTS ix_expense_entry_pay_date
  ON expense_entry(pay_date);

CREATE TRIGGER trg_expense_entry_updated_at
  BEFORE UPDATE ON expense_entry
  FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- ─── 2. RLS — owner + accounts manage; mill_manager + auditor read ──────
ALTER TABLE expense_entry ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS expense_entry_read ON expense_entry;
CREATE POLICY expense_entry_read ON expense_entry
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM app_user u
       WHERE u.id = auth.uid()
         AND u.status = 'active'
         AND u.role IN ('owner','accounts','mill_manager','auditor')
    )
  );

DROP POLICY IF EXISTS expense_entry_write ON expense_entry;
CREATE POLICY expense_entry_write ON expense_entry
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM app_user u
       WHERE u.id = auth.uid()
         AND u.status = 'active'
         AND u.role IN ('owner','accounts')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM app_user u
       WHERE u.id = auth.uid()
         AND u.status = 'active'
         AND u.role IN ('owner','accounts')
    )
  );

-- ─── 3. Line-level allocation view (metres basis) ────────────────────────
CREATE OR REPLACE VIEW v_batch_expense_allocation
  WITH (security_invoker = true) AS
WITH
  batch_window AS (
    SELECT
      pb.id                                        AS batch_id,
      pb.produced_m,
      COALESCE(pb.start_date, pb.created_at::date) AS start_date,
      COALESCE(pb.end_date,   pb.created_at::date) AS end_date
    FROM production_batch pb
    JOIN costing_master cm ON cm.id = pb.costing_id
    WHERE cm.production_mode = 'inhouse'
  ),
  pair_overlap AS (
    SELECT
      ee.id          AS expense_entry_id,
      ee.category,
      ee.amount,
      bw.batch_id,
      bw.produced_m
    FROM expense_entry ee
    JOIN batch_window bw
      ON bw.start_date <= ee.period_end
     AND bw.end_date   >= ee.period_start
  ),
  totals AS (
    SELECT
      expense_entry_id,
      SUM(COALESCE(produced_m, 0)) AS metres_total
    FROM pair_overlap
    GROUP BY expense_entry_id
  )
SELECT
  p.batch_id,
  p.expense_entry_id,
  p.category,
  p.amount AS expense_amount_inr,
  CASE
    WHEN COALESCE(t.metres_total, 0) > 0
      THEN p.amount * (COALESCE(p.produced_m, 0) / t.metres_total)
    ELSE 0
  END AS allocated_expense_inr
FROM pair_overlap p
LEFT JOIN totals t USING (expense_entry_id);

COMMENT ON VIEW v_batch_expense_allocation IS
  'Line-level pro-rata expense allocation: one row per (expense_entry × batch) '
  'overlap. Metres basis only. Vendor batches excluded.';

-- ─── 4. Rolled-up per-batch expense total ────────────────────────────────
CREATE OR REPLACE VIEW v_batch_expense_total
  WITH (security_invoker = true) AS
SELECT
  pb.id AS batch_id,
  pb.batch_code,
  pb.produced_m,
  COALESCE(SUM(vbe.allocated_expense_inr), 0) AS total_expense_inr,
  CASE
    WHEN pb.produced_m > 0
      THEN COALESCE(SUM(vbe.allocated_expense_inr), 0) / pb.produced_m
    ELSE 0
  END AS expense_per_m
FROM production_batch pb
LEFT JOIN v_batch_expense_allocation vbe ON vbe.batch_id = pb.id
GROUP BY pb.id, pb.batch_code, pb.produced_m;

COMMENT ON VIEW v_batch_expense_total IS
  'One row per in-house batch with total allocated mill expenses (₹) and ₹/m.';

COMMIT;
