-- ────────────────────────────────────────────────────────────────────────────
-- Migration 036 — Expense categories table + simplify expense_entry
--
--   Per owner feedback:
--     * Drop `title` and `period_start`/`period_end` from expense_entry.
--       The category name itself is the label; allocation runs against the
--       single `pay_date` (day-of-payment matched to in-house batch windows).
--     * Add `expense_category` table so categories are user-managed
--       (add / rename / soft-delete) rather than hard-coded.
--     * Replace the CHECK constraint on expense_entry.category with a FK
--       reference to expense_category.name.
-- ────────────────────────────────────────────────────────────────────────────

BEGIN;

-- ─── 1. expense_category table ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS expense_category (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       text NOT NULL UNIQUE,
  is_active  boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

DROP TRIGGER IF EXISTS trg_expense_category_updated_at ON expense_category;
CREATE TRIGGER trg_expense_category_updated_at
  BEFORE UPDATE ON expense_category
  FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

INSERT INTO expense_category (name) VALUES
  ('Spares'), ('Carpenter'), ('Electrical'), ('Knotting'),
  ('Auto'), ('Office'), ('Others')
ON CONFLICT (name) DO NOTHING;

ALTER TABLE expense_category ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS expense_category_read ON expense_category;
CREATE POLICY expense_category_read ON expense_category
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM app_user u
              WHERE u.id = auth.uid() AND u.status = 'active'
                AND u.role IN ('owner','accounts','mill_manager','auditor'))
  );

DROP POLICY IF EXISTS expense_category_write ON expense_category;
CREATE POLICY expense_category_write ON expense_category
  FOR ALL USING (
    EXISTS (SELECT 1 FROM app_user u
              WHERE u.id = auth.uid() AND u.status = 'active'
                AND u.role IN ('owner','accounts'))
  ) WITH CHECK (
    EXISTS (SELECT 1 FROM app_user u
              WHERE u.id = auth.uid() AND u.status = 'active'
                AND u.role IN ('owner','accounts'))
  );

-- ─── 2. Simplify expense_entry ───────────────────────────────────────────
ALTER TABLE expense_entry DROP CONSTRAINT IF EXISTS expense_entry_category_check;
ALTER TABLE expense_entry DROP CONSTRAINT IF EXISTS expense_entry_period_order;
ALTER TABLE expense_entry DROP COLUMN IF EXISTS title;
ALTER TABLE expense_entry DROP COLUMN IF EXISTS period_start;
ALTER TABLE expense_entry DROP COLUMN IF EXISTS period_end;

-- ─── 3. Recreate allocation views (now keyed off pay_date) ───────────────
DROP VIEW IF EXISTS v_batch_expense_total;
DROP VIEW IF EXISTS v_batch_expense_allocation;

CREATE OR REPLACE VIEW v_batch_expense_allocation
  WITH (security_invoker = true) AS
WITH
  batch_window AS (
    SELECT
      pb.id                                        AS batch_id,
      pb.produced_m,
      COALESCE(pb.start_date, pb.created_at::date) AS start_date,
      COALESCE(pb.end_date,   pb.created_at::date) AS end_date
    FROM production_batch pb
    JOIN costing_master cm ON cm.id = pb.costing_id
    WHERE cm.production_mode = 'inhouse'
  ),
  pair_overlap AS (
    SELECT
      ee.id        AS expense_entry_id,
      ee.category,
      ee.amount,
      bw.batch_id,
      bw.produced_m
    FROM expense_entry ee
    JOIN batch_window bw
      ON ee.pay_date BETWEEN bw.start_date AND bw.end_date
  ),
  totals AS (
    SELECT expense_entry_id, SUM(COALESCE(produced_m, 0)) AS metres_total
    FROM pair_overlap GROUP BY expense_entry_id
  )
SELECT
  p.batch_id,
  p.expense_entry_id,
  p.category,
  p.amount AS expense_amount_inr,
  CASE
    WHEN COALESCE(t.metres_total, 0) > 0
      THEN p.amount * (COALESCE(p.produced_m, 0) / t.metres_total)
    ELSE 0
  END AS allocated_expense_inr
FROM pair_overlap p
LEFT JOIN totals t USING (expense_entry_id);

CREATE OR REPLACE VIEW v_batch_expense_total
  WITH (security_invoker = true) AS
SELECT
  pb.id AS batch_id,
  pb.batch_code,
  pb.produced_m,
  COALESCE(SUM(vbe.allocated_expense_inr), 0) AS total_expense_inr,
  CASE
    WHEN pb.produced_m > 0
      THEN COALESCE(SUM(vbe.allocated_expense_inr), 0) / pb.produced_m
    ELSE 0
  END AS expense_per_m
FROM production_batch pb
LEFT JOIN v_batch_expense_allocation vbe ON vbe.batch_id = pb.id
GROUP BY pb.id, pb.batch_code, pb.produced_m;

COMMIT;
