-- ─────────────────────────────────────────────────────────────────────────
-- 041_shift_log_weavers_redesign.sql
--
-- The Shift Production Log used to track one weaver name + total metres +
-- downtime minutes per loom-shift. In practice a loom can be run by more
-- than one weaver in the same 12-hour shift (a tea-break swap, a half-shift
-- pair, etc.), and the mill no longer measures downtime — only output.
--
-- This migration drops the downtime tracking, drops the single weaver_name
-- + metres_woven columns on production_shift_log, and adds a child table
-- production_shift_log_weaver where each row is one weaver's individual
-- metres on that loom for that shift. The loom-shift total is the SUM of
-- those child rows.
--
-- Best-effort backfill: any existing (weaver_name, metres_woven) pair that
-- matches an employee by full_name is migrated into the new child table at
-- position 1. Rows that can't be matched are silently dropped (we keep the
-- shift_log row, just without weaver attribution).
--
-- v_loom_shift_utilisation is rebuilt without the uptime % calculation —
-- downtime tracking is gone, so capacity_min / runtime_min / uptime_pct
-- columns are removed.
--
-- Idempotent: safe to re-run. Wrapped in a single transaction.
-- ─────────────────────────────────────────────────────────────────────────

BEGIN;

-- ===========================================================================
-- 1. New child table: per-weaver metres on each shift_log row
-- ===========================================================================
CREATE TABLE IF NOT EXISTS production_shift_log_weaver (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shift_log_id  bigint NOT NULL
                  REFERENCES production_shift_log(id) ON DELETE CASCADE,
  employee_id   bigint NOT NULL REFERENCES employee(id),
  position      smallint NOT NULL DEFAULT 1
                  CHECK (position >= 1),
  metres_woven  numeric(14,2) NOT NULL DEFAULT 0
                  CHECK (metres_woven >= 0),
  created_at    timestamptz NOT NULL DEFAULT NOW(),

  -- One employee can only appear once on the same shift_log row.
  CONSTRAINT uq_pslw_log_emp UNIQUE (shift_log_id, employee_id)
);

CREATE INDEX IF NOT EXISTS idx_pslw_log ON production_shift_log_weaver(shift_log_id);
CREATE INDEX IF NOT EXISTS idx_pslw_emp ON production_shift_log_weaver(employee_id);

COMMENT ON TABLE production_shift_log_weaver IS
  'One row per weaver assigned to a production_shift_log row. '
  'metres_woven = the weaver''s individual output on that loom for that shift. '
  'The loom-shift total is SUM(metres_woven) across rows sharing shift_log_id.';

-- ===========================================================================
-- 2. RLS on the new table — mirror the parent
-- ===========================================================================
ALTER TABLE production_shift_log_weaver ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS p_pslw_select ON production_shift_log_weaver;
CREATE POLICY p_pslw_select ON production_shift_log_weaver FOR SELECT
  USING (EXISTS (SELECT 1 FROM app_user u WHERE u.id = auth.uid()));

DROP POLICY IF EXISTS p_pslw_write ON production_shift_log_weaver;
CREATE POLICY p_pslw_write ON production_shift_log_weaver FOR ALL
  USING (EXISTS (
    SELECT 1 FROM app_user u
    WHERE u.id = auth.uid()
      AND u.role IN ('owner','mill_manager')
  ))
  WITH CHECK (EXISTS (
    SELECT 1 FROM app_user u
    WHERE u.id = auth.uid()
      AND u.role IN ('owner','mill_manager')
  ));

-- ===========================================================================
-- 3. Drop the loom-utilisation view so we can drop the old columns it reads
-- ===========================================================================
DROP VIEW IF EXISTS v_loom_shift_utilisation CASCADE;

-- ===========================================================================
-- 4. Best-effort backfill from the old single-weaver columns
--    Only run when the old columns still exist.
-- ===========================================================================
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name   = 'production_shift_log'
      AND column_name  = 'weaver_name'
  ) THEN
    INSERT INTO production_shift_log_weaver
      (shift_log_id, employee_id, position, metres_woven)
    SELECT
      psl.id,
      e.id,
      1,
      psl.metres_woven
    FROM production_shift_log psl
    JOIN employee e
      ON LOWER(BTRIM(e.full_name)) = LOWER(BTRIM(psl.weaver_name))
    WHERE psl.weaver_name IS NOT NULL
      AND BTRIM(psl.weaver_name) <> ''
      AND psl.metres_woven > 0
    ON CONFLICT (shift_log_id, employee_id) DO NOTHING;
  END IF;
END
$$;

-- ===========================================================================
-- 5. Drop the old constraint + columns on production_shift_log
-- ===========================================================================
ALTER TABLE production_shift_log
  DROP CONSTRAINT IF EXISTS psl_reason_when_downtime;

ALTER TABLE production_shift_log
  DROP COLUMN IF EXISTS downtime_minutes,
  DROP COLUMN IF EXISTS downtime_reason,
  DROP COLUMN IF EXISTS weaver_name,
  DROP COLUMN IF EXISTS metres_woven;

-- ===========================================================================
-- 6. Recreate v_loom_shift_utilisation — metres now sum from the child table,
--    downtime tracking removed.
-- ===========================================================================
CREATE VIEW v_loom_shift_utilisation
WITH (security_invoker = on)
AS
WITH shift_roll AS (
  SELECT
    psl.loom_id,
    COUNT(DISTINCT psl.id)                AS shift_count,
    COALESCE(SUM(pslw.metres_woven), 0)   AS total_metres,
    MAX(psl.log_date)                     AS last_log_date
  FROM production_shift_log psl
  LEFT JOIN production_shift_log_weaver pslw
    ON pslw.shift_log_id = psl.id
  GROUP BY psl.loom_id
)
SELECT
  l.id                                                AS loom_id,
  l.loom_code,
  l.loom_type,
  l.status,
  COALESCE(sr.shift_count, 0)::integer                AS shift_count,
  COALESCE(sr.total_metres, 0)::numeric(14,2)         AS total_metres,
  CASE
    WHEN COALESCE(sr.shift_count, 0) = 0 THEN NULL
    ELSE (sr.total_metres / sr.shift_count)::numeric(14,2)
  END                                                 AS avg_metres_per_shift,
  sr.last_log_date
FROM loom l
LEFT JOIN shift_roll sr ON sr.loom_id = l.id;

COMMENT ON VIEW v_loom_shift_utilisation IS
  'Per-loom shift counts and metres rolled up from production_shift_log + '
  'production_shift_log_weaver. Downtime tracking was removed in 041.';

COMMIT;
