-- 087_fabric_receipt.sql
--
-- Fabric Receipt from jobwork DC.
--
-- When a jobwork DC is confirmed the woven cloth physically comes back to
-- the mill. Fabric Receipt captures that inbound movement: how many
-- metres (or pieces × length) were received, the yarn/bobbin consumption
-- it implies, and the link back to the originating DC so the same DC
-- can't be received twice.
--
-- One fabric_receipt header carries multiple fabric_receipt_item rows
-- (one per fabric quality on the linked DC). Schema mirrors the SMART
-- NT12 "Fabric Receipt" form so the data shape is familiar to operators
-- migrating from that system.
--
-- Stock reductions (pavu metres, yarn_lot kg, bobbin pcs) are applied at
-- save time by app code, not by a DB trigger - keeping the logic in TS
-- lets us FIFO-pick the right rows and surface errors back to the UI.

CREATE TABLE IF NOT EXISTS public.fabric_receipt (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code                text UNIQUE,
  receipt_date        date NOT NULL DEFAULT CURRENT_DATE,
  receipt_type        text NOT NULL DEFAULT 'weaving',
  dc_id               bigint REFERENCES public.delivery_challan(id),
  party_id            bigint REFERENCES public.party(id),
  party_dc_no         text,
  transport_mode      text,
  freight_charges     numeric(14,2) DEFAULT 0,
  empty_beams         integer DEFAULT 0,
  remarks             text,
  total_metres        numeric(14,2) DEFAULT 0,
  total_pieces        integer DEFAULT 0,
  status              text NOT NULL DEFAULT 'received',
  created_at          timestamptz NOT NULL DEFAULT NOW(),
  created_by          uuid REFERENCES public.app_user(id),
  updated_at          timestamptz NOT NULL DEFAULT NOW(),
  updated_by          uuid REFERENCES public.app_user(id)
);

CREATE INDEX IF NOT EXISTS idx_fabric_receipt_dc ON public.fabric_receipt(dc_id);
CREATE INDEX IF NOT EXISTS idx_fabric_receipt_party ON public.fabric_receipt(party_id);
CREATE INDEX IF NOT EXISTS idx_fabric_receipt_date ON public.fabric_receipt(receipt_date);

CREATE TABLE IF NOT EXISTS public.fabric_receipt_item (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  receipt_id          bigint NOT NULL REFERENCES public.fabric_receipt(id) ON DELETE CASCADE,
  sno                 smallint NOT NULL DEFAULT 1,
  fabric_quality_id   bigint REFERENCES public.fabric_quality(id),
  ends_id             bigint REFERENCES public.ends_master(id),
  ends_count_snapshot integer,
  fd_pct              numeric(6,2) DEFAULT 100,
  no_of_pieces        integer DEFAULT 0,
  length_per_pc       numeric(8,2),
  received_metres     numeric(14,2) NOT NULL DEFAULT 0,
  entry_mode          text NOT NULL DEFAULT 'mtr' CHECK (entry_mode IN ('mtr','pcs')),
  weft_yarn_count_id   bigint REFERENCES public.yarn_count(id),
  weft_kg_per_m        numeric(10,4),
  weft_consumed_kg     numeric(14,2),
  porvai_yarn_count_id bigint REFERENCES public.yarn_count(id),
  porvai_kg_per_m      numeric(10,4),
  porvai_consumed_kg   numeric(14,2),
  bobbin_id            bigint REFERENCES public.bobbin(id),
  bobbin_pcs_per_m     numeric(10,4),
  bobbin_consumed_pcs  numeric(14,2),
  product             text,
  qty                 numeric(14,2),
  notes               text
);

CREATE INDEX IF NOT EXISTS idx_fri_receipt ON public.fabric_receipt_item(receipt_id);
CREATE INDEX IF NOT EXISTS idx_fri_quality ON public.fabric_receipt_item(fabric_quality_id);

ALTER TABLE public.delivery_challan
  ADD COLUMN IF NOT EXISTS fabric_receipt_id bigint
    REFERENCES public.fabric_receipt(id);

CREATE INDEX IF NOT EXISTS idx_dc_fabric_receipt
  ON public.delivery_challan(fabric_receipt_id);

INSERT INTO public.doc_sequence (doc_type, prefix, format, fy_code, next_value, reset_yearly)
VALUES ('fabric_receipt', 'FR', '{prefix}/{fy}/{seq:0000}', '26-27', 1, true)
ON CONFLICT (doc_type) DO NOTHING;

CREATE OR REPLACE FUNCTION public.fn_autogen_code()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
DECLARE v_doc_type text;
BEGIN
  IF NEW.code IS NOT NULL AND NEW.code <> '' THEN RETURN NEW; END IF;
  v_doc_type := CASE TG_TABLE_NAME
    WHEN 'customer'           THEN 'cust'
    WHEN 'employee'           THEN 'emp'
    WHEN 'mill'               THEN 'mill'
    WHEN 'vendor'             THEN 'vendor'
    WHEN 'yarn_count'         THEN 'yc'
    WHEN 'ends_master'        THEN 'ends'
    WHEN 'fabric_quality'     THEN 'fq'
    WHEN 'bobbin'             THEN 'bobbin'
    WHEN 'ledger_type'        THEN 'ledger_type'
    WHEN 'ledger_group'       THEN 'ledger_group'
    WHEN 'ledger'             THEN 'ledger'
    WHEN 'fabric_type_master' THEN 'fabric_type'
    WHEN 'jobwork_party'      THEN 'jobwork_party'
    WHEN 'party_type_master'  THEN 'party_type'
    WHEN 'party'              THEN 'party'
    WHEN 'fabric_receipt'     THEN 'fabric_receipt'
    WHEN 'delivery_challan'   THEN
      CASE
        WHEN COALESCE(NEW.production_mode::text, 'inhouse') = 'jobwork'
          THEN 'jobwork_dc'
        ELSE 'dc'
      END
    ELSE NULL
  END;
  IF v_doc_type IS NULL THEN RETURN NEW; END IF;
  NEW.code := fn_next_doc_no(v_doc_type);
  RETURN NEW;
END $function$;

DROP TRIGGER IF EXISTS trg_fabric_receipt_autogen ON public.fabric_receipt;
CREATE TRIGGER trg_fabric_receipt_autogen
  BEFORE INSERT ON public.fabric_receipt
  FOR EACH ROW EXECUTE FUNCTION public.fn_autogen_code();

ALTER TABLE public.fabric_receipt      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fabric_receipt_item ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS p_fr_select ON public.fabric_receipt;
CREATE POLICY p_fr_select ON public.fabric_receipt FOR SELECT USING (true);
DROP POLICY IF EXISTS p_fr_modify ON public.fabric_receipt;
CREATE POLICY p_fr_modify ON public.fabric_receipt FOR ALL USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS p_fri_select ON public.fabric_receipt_item;
CREATE POLICY p_fri_select ON public.fabric_receipt_item FOR SELECT USING (true);
DROP POLICY IF EXISTS p_fri_modify ON public.fabric_receipt_item;
CREATE POLICY p_fri_modify ON public.fabric_receipt_item FOR ALL USING (true) WITH CHECK (true);
