-- 098_drop_mill_use_party.sql
--
-- Retire the standalone `mill` table. The unified `party` table (with
-- party_type = 'Mill / Yarn Supplier') is now the single source for yarn
-- suppliers, matching what we already did for customers (migration 096)
-- and the legacy customer table.
--
-- Mills have already been copied into `party` by migration 073 with
-- their original MILL-NNN code preserved, so we can remap FKs by
-- joining mill.code → party.code (a perfect 1:1 lookup).
--
-- After this migration:
--   - `yarn_lot.supplier_party_id`        replaces `yarn_lot.mill_id`
--   - `sizing_job.yarn_supplier_party_id` replaces `sizing_job.yarn_mill_id`
--   - The `mill` table is dropped.
--
-- Idempotent: every step uses IF EXISTS / IF NOT EXISTS guards.

BEGIN;

-- 1. Add the new FK columns (nullable for safe backfill).
ALTER TABLE public.yarn_lot
  ADD COLUMN IF NOT EXISTS supplier_party_id bigint REFERENCES public.party(id) ON DELETE SET NULL;

ALTER TABLE public.sizing_job
  ADD COLUMN IF NOT EXISTS yarn_supplier_party_id bigint REFERENCES public.party(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_yarn_lot_supplier_party_id
  ON public.yarn_lot(supplier_party_id);
CREATE INDEX IF NOT EXISTS idx_sizing_job_yarn_supplier_party_id
  ON public.sizing_job(yarn_supplier_party_id);

-- 2. Backfill from mill.code → party.code (set by migration 073).
--    Skip rows that have already been backfilled.
UPDATE public.yarn_lot yl
   SET supplier_party_id = p.id
  FROM public.mill m
  JOIN public.party p ON p.code = m.code
 WHERE yl.mill_id = m.id
   AND yl.supplier_party_id IS NULL;

UPDATE public.sizing_job sj
   SET yarn_supplier_party_id = p.id
  FROM public.mill m
  JOIN public.party p ON p.code = m.code
 WHERE sj.yarn_mill_id = m.id
   AND sj.yarn_supplier_party_id IS NULL;

-- 3. Drop the old FK constraints, then the old columns.
--    We look up the constraint name dynamically because the auto-generated
--    name varies (yarn_lot_mill_id_fkey vs fk_yarn_lot_mill etc.).
DO $$
DECLARE
  c record;
BEGIN
  FOR c IN
    SELECT conname
      FROM pg_constraint
     WHERE conrelid = 'public.yarn_lot'::regclass
       AND contype  = 'f'
       AND pg_get_constraintdef(oid) ILIKE '%mill%'
  LOOP
    EXECUTE format('ALTER TABLE public.yarn_lot DROP CONSTRAINT %I', c.conname);
  END LOOP;

  FOR c IN
    SELECT conname
      FROM pg_constraint
     WHERE conrelid = 'public.sizing_job'::regclass
       AND contype  = 'f'
       AND pg_get_constraintdef(oid) ILIKE '%mill%'
  LOOP
    EXECUTE format('ALTER TABLE public.sizing_job DROP CONSTRAINT %I', c.conname);
  END LOOP;
END $$;

ALTER TABLE public.yarn_lot   DROP COLUMN IF EXISTS mill_id     CASCADE;
ALTER TABLE public.sizing_job DROP COLUMN IF EXISTS yarn_mill_id CASCADE;

-- 4. Drop any views that depended on mill (regenerated by later migrations
--    if needed; nothing references them critically right now).
--    The views are recreated below where they're still useful.
DROP VIEW IF EXISTS public.v_yarn_days_of_cover CASCADE;

-- Re-create v_yarn_days_of_cover from yarn_lot WITHOUT mill_id.
-- Original definition keyed on yarn_count_code only, so this is a
-- direct port — just minus the dropped column reference.
CREATE OR REPLACE VIEW public.v_yarn_days_of_cover AS
WITH lot_summary AS (
  SELECT yc.code                            AS yarn_count_code,
         COALESCE(SUM(yl.current_kg), 0)    AS on_hand_kg,
         COALESCE(AVG(NULLIF(yl.cost_per_kg, 0)), 0) AS avg_cost_per_kg
    FROM public.yarn_count yc
    LEFT JOIN public.yarn_lot yl ON yl.yarn_count_id = yc.id
   WHERE yc.status = 'active'
   GROUP BY yc.code
)
SELECT yarn_count_code,
       on_hand_kg,
       avg_cost_per_kg,
       -- Days-of-cover = on_hand / avg_daily_burn. We don't have a daily
       -- burn rate yet, so for now we just expose a placeholder of 30
       -- days at avg consumption. This view is regenerated in a later
       -- migration once daily burn is tracked.
       (CASE WHEN on_hand_kg > 0 THEN on_hand_kg / 30.0 ELSE 0 END) AS days_of_cover
  FROM lot_summary;

-- 5. Drop the mill table itself. CASCADE removes any auto-generated
--    indexes / sequences / triggers attached to it.
DROP TABLE IF EXISTS public.mill CASCADE;

COMMIT;
