-- 201_agent_commission.sql
--
-- Agent / broker commission on fabric (tax) invoices.
--
-- One commission row per invoice: the operator picks a Broker/Agent party and
-- a commission (per piece, per metre, or a percentage of the taxable value).
-- The computed amount is a PAYABLE we owe the agent, so it surfaces in the
-- dashboard "Outstanding Supplier Payables" and is settled on the Payments
-- screen — tracked via amount_paid / balance just like the other bill tables.

CREATE TABLE IF NOT EXISTS public.agent_commission (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id      bigint NOT NULL UNIQUE REFERENCES public.invoice(id) ON DELETE CASCADE,
  agent_party_id  bigint NOT NULL REFERENCES public.party(id),
  commission_type text   NOT NULL CHECK (commission_type IN ('pcs','metre','percent')),
  commission_rate numeric(12,4) NOT NULL CHECK (commission_rate >= 0),
  amount          numeric(14,2) NOT NULL CHECK (amount >= 0),
  amount_paid     numeric(14,2) NOT NULL DEFAULT 0 CHECK (amount_paid >= 0),
  balance         numeric(14,2) GENERATED ALWAYS AS (amount - amount_paid) STORED,
  status          text   NOT NULL DEFAULT 'active',
  created_at      timestamptz NOT NULL DEFAULT now(),
  created_by      uuid REFERENCES public.app_user(id),
  updated_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_agent_commission_agent   ON public.agent_commission(agent_party_id);
CREATE INDEX IF NOT EXISTS idx_agent_commission_invoice ON public.agent_commission(invoice_id);

CREATE TABLE IF NOT EXISTS public.payment_agent_allocation (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_id          bigint NOT NULL REFERENCES public.payment(id) ON DELETE CASCADE,
  agent_commission_id bigint NOT NULL REFERENCES public.agent_commission(id) ON DELETE CASCADE,
  amount              numeric(14,2) NOT NULL CHECK (amount > 0),
  created_at          timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_pay_agent_alloc_commission ON public.payment_agent_allocation(agent_commission_id);
CREATE INDEX IF NOT EXISTS idx_pay_agent_alloc_payment    ON public.payment_agent_allocation(payment_id);

-- Keep agent_commission.amount_paid in sync with its allocations.
CREATE OR REPLACE FUNCTION public.fn_sync_agent_commission_paid()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE v_id bigint;
BEGIN
  v_id := COALESCE(NEW.agent_commission_id, OLD.agent_commission_id);
  UPDATE public.agent_commission ac
     SET amount_paid = COALESCE(
           (SELECT sum(amount) FROM public.payment_agent_allocation
             WHERE agent_commission_id = v_id), 0),
         updated_at = now()
   WHERE ac.id = v_id;
  RETURN NULL;
END $$;

DROP TRIGGER IF EXISTS trg_pay_agent_alloc_sync ON public.payment_agent_allocation;
CREATE TRIGGER trg_pay_agent_alloc_sync
  AFTER INSERT OR UPDATE OR DELETE ON public.payment_agent_allocation
  FOR EACH ROW EXECUTE FUNCTION public.fn_sync_agent_commission_paid();

-- RLS — mirror invoice / payment access.
ALTER TABLE public.agent_commission        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_agent_allocation ENABLE ROW LEVEL SECURITY;

CREATE POLICY p_agent_commission_read ON public.agent_commission FOR SELECT
  USING (current_user_role() IN ('owner','auditor','sales_manager','accounts','mill_manager'));
CREATE POLICY p_agent_commission_write ON public.agent_commission FOR ALL
  USING (current_user_role() IN ('owner','accounts','sales_manager'));

CREATE POLICY p_pay_agent_alloc_read ON public.payment_agent_allocation FOR SELECT
  USING (current_user_role() IN ('owner','auditor','accounts','sales_manager'));
CREATE POLICY p_pay_agent_alloc_write ON public.payment_agent_allocation FOR ALL
  USING (current_user_role() IN ('owner','accounts'));
