-- 219_employee_loan.sql
--
-- Employee loans (advances against future wages).
--
--   The owner lends cash to a worker; it gets paid back by deducting from
--   the worker's weekly wage over time. Until now there was no record of
--   who owes what, and the cash that physically left the till when a loan
--   was issued never showed up as an outflow.
--
-- This migration adds two pieces:
--
--   1. employee_loan table — one row per loan DISBURSEMENT (cash given out).
--      Each row records which cash/bank account the money came from
--      (source_ledger_id) so the Ledger View can project it as a Credit
--      (outflow) on that account, exactly like wages/expenses (migration 218).
--      A BEFORE INSERT trigger defaults source_ledger_id to CASH.
--
--   2. wage_entry.loan_deduction — how much of a wage payment was withheld
--      to repay the worker's loan. The cash actually handed over is
--      (amount - loan_deduction); the withheld part reduces the outstanding
--      loan. Repayments are therefore DERIVED from wage rows — no separate
--      repayment table.
--
--   Outstanding loan for an employee:
--      SUM(employee_loan.amount) - SUM(wage_entry.loan_deduction)
--
-- Safe to re-run: CREATE ... IF NOT EXISTS / OR REPLACE everywhere;
-- ADD COLUMN IF NOT EXISTS for the wage_entry column.

BEGIN;

-- ─── 1. employee_loan table ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.employee_loan (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id      bigint NOT NULL REFERENCES public.employee(id),
  loan_date        date NOT NULL DEFAULT CURRENT_DATE,
  amount           numeric(12,2) NOT NULL,
  source_ledger_id bigint REFERENCES public.ledger(id) ON DELETE SET NULL,
  notes            text,
  created_at       timestamptz NOT NULL DEFAULT now(),
  created_by       uuid REFERENCES public.app_user(id),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  updated_by       uuid REFERENCES public.app_user(id),
  CONSTRAINT employee_loan_amount_pos CHECK (amount > 0)
);

COMMENT ON TABLE public.employee_loan IS
  'Employee loans / advances. One row per cash DISBURSEMENT given to a worker. '
  'Repayments are not stored here — they are deductions on wage_entry rows '
  '(wage_entry.loan_deduction). Outstanding = SUM(amount) - SUM(deductions). '
  'source_ledger_id records which cash/bank account the money came from so '
  'the Ledger View shows it as a Credit (outflow). (migration 219)';

COMMENT ON COLUMN public.employee_loan.source_ledger_id IS
  'Cash / bank account this loan was paid out from. Defaults to CASH via '
  'fn_employee_loan_default_source trigger. Shows as a Credit on that ledger '
  'in the Ledger View.';

CREATE INDEX IF NOT EXISTS idx_employee_loan_employee      ON public.employee_loan(employee_id);
CREATE INDEX IF NOT EXISTS idx_employee_loan_loan_date     ON public.employee_loan(loan_date);
CREATE INDEX IF NOT EXISTS idx_employee_loan_source_ledger ON public.employee_loan(source_ledger_id);

DROP TRIGGER IF EXISTS trg_employee_loan_updated_at ON public.employee_loan;
CREATE TRIGGER trg_employee_loan_updated_at
  BEFORE UPDATE ON public.employee_loan
  FOR EACH ROW EXECUTE FUNCTION public.fn_set_updated_at();

-- ─── 2. Default-on-insert trigger → CASH (mirrors migration 218) ─────────
CREATE OR REPLACE FUNCTION public.fn_employee_loan_default_source()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE v_ledger_id bigint;
BEGIN
  IF NEW.source_ledger_id IS NOT NULL THEN RETURN NEW; END IF;
  SELECT l.id INTO v_ledger_id
    FROM public.ledger l
    JOIN public.ledger_type lt ON lt.id = l.type_id
   WHERE lt.name = 'CASH'
   ORDER BY l.id
   LIMIT 1;
  NEW.source_ledger_id := v_ledger_id;
  RETURN NEW;
END
$$;

DROP TRIGGER IF EXISTS trg_employee_loan_default_source ON public.employee_loan;
CREATE TRIGGER trg_employee_loan_default_source
  BEFORE INSERT ON public.employee_loan
  FOR EACH ROW EXECUTE FUNCTION public.fn_employee_loan_default_source();

-- ─── 3. RLS — owner + accounts manage; mill_manager + auditor read ───────
ALTER TABLE public.employee_loan ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS employee_loan_read ON public.employee_loan;
CREATE POLICY employee_loan_read ON public.employee_loan
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.app_user u
       WHERE u.id = auth.uid()
         AND u.status = 'active'
         AND u.role IN ('owner','accounts','mill_manager','auditor')
    )
  );

DROP POLICY IF EXISTS employee_loan_write ON public.employee_loan;
CREATE POLICY employee_loan_write ON public.employee_loan
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.app_user u
       WHERE u.id = auth.uid()
         AND u.status = 'active'
         AND u.role IN ('owner','accounts')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.app_user u
       WHERE u.id = auth.uid()
         AND u.status = 'active'
         AND u.role IN ('owner','accounts')
    )
  );

-- ─── 4. wage_entry.loan_deduction — repayment withheld from a wage ───────
ALTER TABLE public.wage_entry
  ADD COLUMN IF NOT EXISTS loan_deduction numeric(12,2) NOT NULL DEFAULT 0;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'wage_entry_loan_deduction_nonneg'
  ) THEN
    ALTER TABLE public.wage_entry
      ADD CONSTRAINT wage_entry_loan_deduction_nonneg CHECK (loan_deduction >= 0);
  END IF;
END $$;

COMMENT ON COLUMN public.wage_entry.loan_deduction IS
  'Amount of this wage withheld to repay the employee''s loan. Cash actually '
  'paid out = amount - loan_deduction. Reduces the employee''s outstanding '
  'employee_loan balance. (migration 219)';

COMMIT;
