-- 313: Yarn transfer between warehouses
-- Moves weft yarn between Sizing warehouse, In-house warehouse and an
-- Outsource / Job-work weaver. A transfer is NOT a purchase: the
-- destination copy carries no supplier, no invoice and no amount, so
-- it never shows on the purchase register, payables or GST.
--   to in_house / sizing -> new yarn_lot (transfer_id set)
--   to weaver            -> new jobwork_weft_bag (consumed by that
--                           weaver's fabric receipts, FIFO)
--   from in_house        -> yarn_lot.current_kg FIFO + stock_ledger out
--   from sizing          -> sizing yarn_lot.current_kg FIFO (warehouse
--                           page reads the transfer row as the outflow)
--   from weaver          -> jobwork_weft_bag.total_kg FIFO + ledger out

CREATE TABLE IF NOT EXISTS public.yarn_transfer (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transfer_code  text UNIQUE,
  transfer_date  date NOT NULL DEFAULT CURRENT_DATE,
  yarn_count_id  bigint NOT NULL,
  kg             numeric(12,3) NOT NULL CHECK (kg > 0),
  bag_count      integer NOT NULL DEFAULT 0 CHECK (bag_count >= 0),
  from_loc       text NOT NULL CHECK (from_loc IN ('sizing','in_house','outsource')),
  to_loc         text NOT NULL CHECK (to_loc   IN ('sizing','in_house','outsource')),
  from_party_id  bigint,
  to_party_id    bigint,
  cost_per_kg    numeric(12,2),
  source_cuts    jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_lot_id bigint,
  created_bag_id bigint,
  notes          text,
  created_at     timestamptz NOT NULL DEFAULT now(),
  created_by     uuid DEFAULT auth.uid(),
  CONSTRAINT yarn_transfer_from_party_chk CHECK ((from_loc = 'outsource') = (from_party_id IS NOT NULL)),
  CONSTRAINT yarn_transfer_to_party_chk   CHECK ((to_loc   = 'outsource') = (to_party_id   IS NOT NULL)),
  CONSTRAINT yarn_transfer_diff_chk CHECK (from_loc <> to_loc OR from_party_id IS DISTINCT FROM to_party_id)
);

ALTER TABLE public.yarn_transfer ADD CONSTRAINT yarn_transfer_count_fk FOREIGN KEY (yarn_count_id) REFERENCES public.yarn_count(id) NOT VALID;
ALTER TABLE public.yarn_transfer ADD CONSTRAINT yarn_transfer_from_party_fk FOREIGN KEY (from_party_id) REFERENCES public.jobwork_party(id) NOT VALID;
ALTER TABLE public.yarn_transfer ADD CONSTRAINT yarn_transfer_to_party_fk FOREIGN KEY (to_party_id) REFERENCES public.jobwork_party(id) NOT VALID;

ALTER TABLE public.yarn_transfer ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS p_yarn_transfer_select ON public.yarn_transfer;
CREATE POLICY p_yarn_transfer_select ON public.yarn_transfer FOR SELECT USING (true);
DROP POLICY IF EXISTS p_yarn_transfer_write ON public.yarn_transfer;
CREATE POLICY p_yarn_transfer_write ON public.yarn_transfer FOR ALL
  USING (current_user_role() = ANY (ARRAY['owner'::user_role, 'mill_manager'::user_role]))
  WITH CHECK (current_user_role() = ANY (ARRAY['owner'::user_role, 'mill_manager'::user_role]));

ALTER TABLE public.yarn_lot         ADD COLUMN IF NOT EXISTS transfer_id bigint;
ALTER TABLE public.jobwork_weft_bag ADD COLUMN IF NOT EXISTS transfer_id bigint;

CREATE OR REPLACE FUNCTION public.fn_yarn_transfer_create(
  p_date date, p_count bigint, p_kg numeric, p_bags integer,
  p_from text, p_to text, p_from_party bigint, p_to_party bigint, p_notes text
) RETURNS bigint
LANGUAGE plpgsql SECURITY INVOKER SET search_path = public AS $$
DECLARE
  v_id bigint; v_code text; v_remaining numeric := p_kg; v_cut numeric;
  v_cuts jsonb := '[]'::jsonb; v_cost_sum numeric := 0; v_cost_kg numeric := 0;
  v_cost numeric; v_lot_id bigint; v_bag_id bigint; r record;
  v_from_label text; v_to_label text;
BEGIN
  IF p_kg IS NULL OR p_kg <= 0 THEN RAISE EXCEPTION 'Enter the kg to transfer.'; END IF;
  IF p_count IS NULL THEN RAISE EXCEPTION 'Pick the yarn count.'; END IF;

  v_from_label := CASE p_from WHEN 'sizing' THEN 'Sizing warehouse' WHEN 'in_house' THEN 'In-house warehouse'
                  ELSE (SELECT name FROM jobwork_party WHERE id = p_from_party) END;
  v_to_label   := CASE p_to WHEN 'sizing' THEN 'Sizing warehouse' WHEN 'in_house' THEN 'In-house warehouse'
                  ELSE (SELECT name FROM jobwork_party WHERE id = p_to_party) END;

  INSERT INTO yarn_transfer (transfer_date, yarn_count_id, kg, bag_count, from_loc, to_loc,
                             from_party_id, to_party_id, notes)
  VALUES (COALESCE(p_date, CURRENT_DATE), p_count, p_kg, COALESCE(p_bags, 0), p_from, p_to,
          CASE WHEN p_from = 'outsource' THEN p_from_party END,
          CASE WHEN p_to   = 'outsource' THEN p_to_party END, NULLIF(trim(p_notes), ''))
  RETURNING id INTO v_id;
  v_code := 'YT-' || lpad(v_id::text, 4, '0');

  -- ── Source side ──────────────────────────────────────────────
  IF p_from IN ('in_house', 'sizing') THEN
    FOR r IN SELECT id, current_kg, cost_per_kg FROM yarn_lot
             WHERE yarn_count_id = p_count AND yarn_kind = 'yarn'
               AND delivery_destination = p_from AND current_kg > 0
             ORDER BY received_date, id FOR UPDATE LOOP
      EXIT WHEN v_remaining <= 0;
      v_cut := LEAST(r.current_kg, v_remaining);
      UPDATE yarn_lot SET current_kg = current_kg - v_cut WHERE id = r.id;
      v_cuts := v_cuts || jsonb_build_object('t', 'lot', 'id', r.id, 'kg', v_cut);
      v_cost_sum := v_cost_sum + v_cut * r.cost_per_kg; v_cost_kg := v_cost_kg + v_cut;
      v_remaining := v_remaining - v_cut;
    END LOOP;
    IF p_from = 'in_house' THEN
      INSERT INTO stock_ledger (bucket, direction, jobwork_party_id, yarn_count_id, quantity, unit,
                                event_date, source_kind, source_id, reference_no, notes)
      VALUES ('weft_yarn', 'out', NULL, p_count, p_kg, 'kg', COALESCE(p_date, CURRENT_DATE),
              'yarn_transfer', v_id, v_code, 'Transfer to ' || COALESCE(v_to_label, '?'));
    END IF;
  ELSE
    FOR r IN SELECT id, total_kg FROM jobwork_weft_bag
             WHERE jobwork_party_id = p_from_party AND yarn_count_id = p_count AND total_kg > 0
             ORDER BY given_date, id FOR UPDATE LOOP
      EXIT WHEN v_remaining <= 0;
      v_cut := LEAST(r.total_kg, v_remaining);
      UPDATE jobwork_weft_bag SET total_kg = total_kg - v_cut WHERE id = r.id;
      v_cuts := v_cuts || jsonb_build_object('t', 'bag', 'id', r.id, 'kg', v_cut);
      v_remaining := v_remaining - v_cut;
    END LOOP;
    INSERT INTO stock_ledger (bucket, direction, jobwork_party_id, yarn_count_id, quantity, unit,
                              event_date, source_kind, source_id, reference_no, notes)
    VALUES ('weft_yarn', 'out', p_from_party, p_count, p_kg, 'kg', COALESCE(p_date, CURRENT_DATE),
            'yarn_transfer', v_id, v_code, 'Transfer to ' || COALESCE(v_to_label, '?'));
  END IF;

  -- Cost travels with the yarn: weighted cost of the lots it came
  -- from, else the latest purchase rate for this count.
  IF v_cost_kg > 0 THEN v_cost := round(v_cost_sum / v_cost_kg, 2);
  ELSE
    SELECT cost_per_kg INTO v_cost FROM yarn_lot
     WHERE yarn_count_id = p_count AND cost_per_kg > 0
     ORDER BY received_date DESC, id DESC LIMIT 1;
  END IF;
  v_cost := COALESCE(NULLIF(v_cost, 0), 1);

  -- ── Destination side ─────────────────────────────────────────
  IF p_to IN ('in_house', 'sizing') THEN
    INSERT INTO yarn_lot (lot_code, yarn_count_id, received_date, received_kg, current_kg, cost_per_kg,
                          delivery_destination, yarn_kind, bag_count, notes, transfer_id, created_by)
    VALUES (v_code, p_count, COALESCE(p_date, CURRENT_DATE), p_kg, p_kg, v_cost, p_to, 'yarn',
            COALESCE(p_bags, 0), 'Transfer from ' || COALESCE(v_from_label, '?'), v_id, auth.uid())
    RETURNING id INTO v_lot_id;
  ELSE
    INSERT INTO jobwork_weft_bag (jobwork_party_id, yarn_count_id, given_date, bag_count, total_kg,
                                  reference_no, notes, transfer_id, created_by)
    VALUES (p_to_party, p_count, COALESCE(p_date, CURRENT_DATE), NULLIF(COALESCE(p_bags, 0), 0), p_kg,
            v_code, 'Transfer from ' || COALESCE(v_from_label, '?'), v_id, auth.uid())
    RETURNING id INTO v_bag_id;
  END IF;

  UPDATE yarn_transfer SET transfer_code = v_code, cost_per_kg = v_cost, source_cuts = v_cuts,
         created_lot_id = v_lot_id, created_bag_id = v_bag_id
   WHERE id = v_id;
  RETURN v_id;
END $$;

-- Deleting a transfer is done by the app (lib/yarn-transfer.ts ->
-- deleteYarnTransfer): it refuses if the destination copy is already
-- partly used, restores the FIFO cuts from source_cuts, and removes
-- the ledger row, the created lot / bag and the transfer row.

GRANT EXECUTE ON FUNCTION public.fn_yarn_transfer_create(date, bigint, numeric, integer, text, text, bigint, bigint, text) TO authenticated;

-- Transport copy (print) details, filled by the app after create.
ALTER TABLE public.yarn_transfer ADD COLUMN IF NOT EXISTS vehicle_no text, ADD COLUMN IF NOT EXISTS purchase_lot_id bigint;
