-- 314: Empty beam tracking (count based — PPK beams carry no number).
-- All beams belong to PPK TEX and move only between the godown, the
-- sizing mill and our own looms. Where a beam is right now is DERIVED:
--   total owned      = opening.qty + added - removed
--   at sizing (empty)= opening.at_sizing_qty + sent_to_sizing
--                      - returned_from_sizing
--                      - paavus received from sizing after the opening
--   sized paavu stock= pavu (in_house, in_stock)
--   on looms         = pavu (in_house, on_loom)
--   empty in godown  = total - the three above
-- A finished paavu frees its beam back to the godown automatically.

CREATE TABLE IF NOT EXISTS public.beam_movement (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code          text UNIQUE,
  move_date     date NOT NULL DEFAULT CURRENT_DATE,
  kind          text NOT NULL CHECK (kind IN ('opening','sent_to_sizing','returned_from_sizing','added','removed')),
  qty           integer NOT NULL CHECK (qty >= 0),
  at_sizing_qty integer NOT NULL DEFAULT 0 CHECK (at_sizing_qty >= 0),
  party_id      bigint,
  vehicle_no    text,
  notes         text,
  created_at    timestamptz NOT NULL DEFAULT now(),
  created_by    uuid DEFAULT auth.uid()
);
ALTER TABLE public.beam_movement ADD CONSTRAINT beam_movement_party_fk FOREIGN KEY (party_id) REFERENCES public.party(id) NOT VALID;

ALTER TABLE public.beam_movement ENABLE ROW LEVEL SECURITY;
CREATE POLICY p_beam_movement_select ON public.beam_movement FOR SELECT USING (true);
CREATE POLICY p_beam_movement_write ON public.beam_movement FOR ALL
  USING (current_user_role() = ANY (ARRAY['owner'::user_role, 'mill_manager'::user_role]))
  WITH CHECK (current_user_role() = ANY (ARRAY['owner'::user_role, 'mill_manager'::user_role]));

CREATE OR REPLACE FUNCTION public.tg_beam_movement_code() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.code IS NULL OR NEW.code = '' THEN NEW.code := 'BG-' || lpad(NEW.id::text, 4, '0'); END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER trg_beam_movement_code BEFORE INSERT ON public.beam_movement
  FOR EACH ROW EXECUTE FUNCTION public.tg_beam_movement_code();
