'use client';
/**
 * Receive Fabric form (CORR-P5)
 *
 * Records a vendor fabric delivery against an outsource_order by:
 *   1. Inserting a production_batch row (loom_id=NULL, outsource_order_id=this OW)
 *      with actual_pick_cost_per_m frozen to ow.pick_paise_agreed and
 *      warp/weft/porvai/bobbin copied from the OW.
 *   2. Updating outsource_order.delivered_metres and status.
 *
 * The snapshot trigger on production_batch will fill the other actual_* columns
 * from costing + lot data.
 */
import { useState, type FormEvent } from 'react';
import { useRouter } from 'next/navigation';
import { createClient } from '@/lib/supabase/client';
import { Loader2 } from 'lucide-react';

interface ReceiveFabricFormProps {
  owId: number;
  owNumber: string;
  costingId: number;
  pickPaiseAgreed: number;
  warpLotId: number | null;
  weftLotId: number | null;
  porvaiLotId: number | null;
  bobbin1Id: number | null;
  expectedM: number;
  deliveredSoFar: number;
}

const today = (): string => new Date().toISOString().slice(0, 10);

export function ReceiveFabricForm({
  owId,
  owNumber,
  costingId,
  pickPaiseAgreed,
  warpLotId,
  weftLotId,
  porvaiLotId,
  bobbin1Id,
  expectedM,
  deliveredSoFar,
}: ReceiveFabricFormProps): React.ReactElement {
  const router = useRouter();
  const supabase = createClient();

  const remaining = Math.max(0, expectedM - deliveredSoFar);

  const [receivedM, setReceivedM] = useState('');
  const [rejectedM, setRejectedM] = useState('0');
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate]     = useState(today());
  const [bobbinReturnedPcs, setBobbinReturnedPcs] = useState('0');
  const [notes, setNotes] = useState('');

  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function onSubmit(e: FormEvent): Promise<void> {
    e.preventDefault();
    setError(null);

    const m = Number(receivedM);
    if (!receivedM || m <= 0) { setError('Received metres must be > 0.'); return; }

    setBusy(true);
    try {
      // 1. Insert the production_batch row tied to this OW.
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const { error: insErr } = await (supabase as any)
        .from('production_batch')
        .insert({
          // batch_code auto-generated by migration 008 trigger
          batch_code: '',
          costing_id: costingId,
          outsource_order_id: owId,
          loom_id: null,
          warp_lot_id: warpLotId,
          weft_lot_id: weftLotId,
          porvai_lot_id: porvaiLotId,
          bobbin_1_id: bobbin1Id,
          start_date: startDate || null,
          end_date: endDate || null,
          produced_m: m,
          rejected_m: Number(rejectedM || 0),
          // Freeze the vendor's negotiated pick paise as the actual loom cost.
          actual_pick_cost_per_m: pickPaiseAgreed,
          notes: notes || `Vendor delivery against ${owNumber}`,
        });
      if (insErr) { setError(insErr.message); setBusy(false); return; }

      // 2. Update the OW: delivered_metres, status, bobbin_pcs_returned.
      const newDelivered = deliveredSoFar + m;
      const newStatus: 'partial' | 'complete' =
        newDelivered + 0.5 >= expectedM ? 'complete' : 'partial';

      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const { error: upErr } = await (supabase as any)
        .from('outsource_order')
        .update({
          delivered_metres: newDelivered,
          delivered_date: endDate || today(),
          status: newStatus,
          bobbin_pcs_returned: Number(bobbinReturnedPcs || 0),
        })
        .eq('id', owId);
      if (upErr) { setError(upErr.message); setBusy(false); return; }

      router.refresh();
      setReceivedM('');
      setRejectedM('0');
      setBobbinReturnedPcs('0');
      setNotes('');
      setBusy(false);
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'Could not record receipt.');
      setBusy(false);
    }
  }

  return (
    <form onSubmit={onSubmit} className="card p-4 space-y-3">
      <div className="flex items-baseline justify-between">
        <h3 className="text-sm font-semibold text-ink-soft uppercase tracking-wide">
          Record fabric received
        </h3>
        <div className="text-xs text-ink-mute">
          Remaining: <span className="num font-semibold">{remaining.toFixed(0)} m</span>
        </div>
      </div>

      <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3">
        <div>
          <label className="label">Received m *</label>
          <input type="number" min="0" step="0.01" required
                 value={receivedM} onChange={e => setReceivedM(e.target.value)}
                 className="input num" />
        </div>
        <div>
          <label className="label">Rejected m</label>
          <input type="number" min="0" step="0.01"
                 value={rejectedM} onChange={e => setRejectedM(e.target.value)}
                 className="input num" />
        </div>
        <div>
          <label className="label">Start date</label>
          <input type="date" value={startDate}
                 onChange={e => setStartDate(e.target.value)} className="input" />
        </div>
        <div>
          <label className="label">End / receipt date</label>
          <input type="date" value={endDate}
                 onChange={e => setEndDate(e.target.value)} className="input" />
        </div>
        <div>
          <label className="label">Bobbin pcs returned (cumulative)</label>
          <input type="number" min="0" step="0.01"
                 value={bobbinReturnedPcs}
                 onChange={e => setBobbinReturnedPcs(e.target.value)}
                 className="input num" />
        </div>
        <div className="sm:col-span-2 lg:col-span-3">
          <label className="label">Notes</label>
          <input value={notes} onChange={e => setNotes(e.target.value)}
                 className="input" placeholder={`Vendor delivery against ${owNumber}`} />
        </div>
      </div>

      <div className="rounded-lg bg-cloud/60 border border-line/60 p-3 text-xs">
        Cost snapshot: <span className="num font-semibold">₹{pickPaiseAgreed.toFixed(4)}/m</span>{' '}
        will be frozen as the actual loom cost on the new batch.
        Warp + weft + sizing + overhead come from the costing + lot data, same as in-house batches.
      </div>

      {error && (
        <div className="text-sm text-err">{error}</div>
      )}

      <div className="flex justify-end">
        <button type="submit" className="btn-primary" disabled={busy}>
          {busy ? (<><Loader2 className="w-4 h-4 animate-spin" /> Saving…</>) : 'Record receipt'}
        </button>
      </div>
    </form>
  );
}
