'use client';
/**
 * Fabric Receipt — record a finished production batch.
 *
 * Flow:
 *   1. Pick the costing (quality) being woven.
 *   2. Pick the active pavu_assign — this row drives the warp side:
 *        • loom_id is auto-set from pavu_assign.loom_id
 *        • warp_lot_id is auto-set from sizing_job.yarn_lot_id
 *        • the cost-snapshot trigger (007) uses pavu_assign_id to snapshot
 *          sizing_rate_per_kg from sizing_job.
 *      If the beam was outsourced or you skipped pavu, you can still pick
 *      loom + warp_lot manually.
 *   3. Pick weft + porvai yarn lots and bobbins (optional, depends on costing).
 *   4. Enter produced m, rejected m, start/end dates, notes.
 *
 * On submit:
 *   • batch_code is auto-generated by trigger (migration 008).
 *   • actual_warp/weft/porvai/sizing/pick/overhead/bobbin/true cost columns
 *     are filled by fn_snapshot_batch_cost (migrations 005-007).
 *   • The form leaves them NULL on the payload so the trigger owns them.
 */
import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { useRouter } from 'next/navigation';
import { createClient } from '@/lib/supabase/client';
import { PageHeader } from '@/app/components/page-header';
import { Loader2, ArrowLeft } from 'lucide-react';
import Link from 'next/link';
import type { Database } from '@/lib/database.types';

type ProductionBatchInsert = Database['public']['Tables']['production_batch']['Insert'];

interface Costing {
  id: number;
  quality_code: string;
  quality_name: string;
  approval_status: string;
  use_bobbin_1: boolean | null;
  use_bobbin_2: boolean | null;
  use_porvai: boolean | null;
}

interface ActivePavuAssign {
  id: number;
  loom_id: number;
  status: string;
  start_date: string | null;
  loom: { id: number; loom_code: string } | null;
  pavu: {
    id: number;
    pavu_code: string;
    beam_no: string;
    meters: number;
    sizing_job: {
      id: number;
      job_code: string;
      sizing_rate_per_kg: number;
      yarn_lot_id: number | null;
    } | null;
  } | null;
}

interface Loom {
  id: number;
  loom_code: string;
  status: string;
}

interface YarnLot {
  id: number;
  lot_code: string;
  current_kg: number;
  cost_per_kg: number;
  yarn_count_id: number;
  mill_id: number;
}

interface Bobbin {
  id: number;
  code: string;
  description: string;
  is_lurex: boolean;
}

interface SalesOrderLine {
  id: number;
  costing_id: number;
  quantity_m: number;
  delivered_m: number;
  sales_order: { id: number; so_number: string } | null;
}

interface CostingPreview {
  quoted_cost_per_m: number | null;
  true_cost_per_m: number | null;
  sizing_cost_per_m: number | null;
  warp_cost_per_m: number | null;
  weft_cost_per_m: number | null;
}

const today = (): string => new Date().toISOString().slice(0, 10);

export default function NewFabricReceiptPage() {
  const router = useRouter();
  const supabase = createClient();

  // ── master data ───────────────────────────────────────────────────────────
  const [costings, setCostings] = useState<Costing[]>([]);
  const [assigns, setAssigns] = useState<ActivePavuAssign[]>([]);
  const [looms, setLooms] = useState<Loom[]>([]);
  const [lots, setLots] = useState<YarnLot[]>([]);
  const [bobbins, setBobbins] = useState<Bobbin[]>([]);
  const [soLines, setSoLines] = useState<SalesOrderLine[]>([]);
  const [loading, setLoading] = useState(true);

  // ── form state ────────────────────────────────────────────────────────────
  const [costingId, setCostingId] = useState('');
  const [soLineId, setSoLineId] = useState('');

  const [pavuAssignId, setPavuAssignId] = useState('');
  const [loomId, setLoomId] = useState('');
  const [warpLotId, setWarpLotId] = useState('');

  const [weftLotId, setWeftLotId] = useState('');
  const [porvaiLotId, setPorvaiLotId] = useState('');

  const [bobbin1Id, setBobbin1Id] = useState('');
  const [bobbin2Id, setBobbin2Id] = useState('');

  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState(today());
  const [producedM, setProducedM] = useState('');
  const [rejectedM, setRejectedM] = useState('0');
  const [notes, setNotes] = useState('');

  const [preview, setPreview] = useState<CostingPreview | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // ── load master data ──────────────────────────────────────────────────────
  useEffect(() => {
    (async () => {
      const [c, a, l, y, b, s] = await Promise.all([
        supabase
          .from('costing_master')
          .select('id, quality_code, quality_name, approval_status, use_bobbin_1, use_bobbin_2, use_porvai')
          .eq('approval_status', 'approved')
          .order('quality_code'),
        supabase
          .from('pavu_assign')
          .select(`
            id, loom_id, status, start_date,
            loom:loom_id ( id, loom_code ),
            pavu:pavu_id (
              id, pavu_code, beam_no, meters,
              sizing_job:sizing_job_id ( id, job_code, sizing_rate_per_kg, yarn_lot_id )
            )
          `)
          .in('status', ['mounted', 'running', 'completed'])
          .order('start_date', { ascending: false })
          .limit(50),
        supabase.from('loom').select('id, loom_code, status').order('loom_code'),
        supabase
          .from('yarn_lot')
          .select('id, lot_code, current_kg, cost_per_kg, yarn_count_id, mill_id')
          .gt('current_kg', 0)
          .order('received_date', { ascending: false })
          .limit(200),
        supabase.from('bobbin').select('id, code, description, is_lurex').eq('status', 'active').order('code'),
        supabase
          .from('sales_order_line')
          .select(`
            id, costing_id, quantity_m, delivered_m,
            sales_order:so_id ( id, so_number )
          `)
          .order('id', { ascending: false })
          .limit(100),
      ]);

      setCostings(c.data ?? []);
      setAssigns((a.data as unknown as ActivePavuAssign[]) ?? []);
      setLooms(l.data ?? []);
      setLots(y.data ?? []);
      setBobbins(b.data ?? []);
      setSoLines((s.data as unknown as SalesOrderLine[]) ?? []);
      setLoading(false);
    })();
  }, [supabase]);

  // ── derived: chosen costing meta ──────────────────────────────────────────
  const chosenCosting = useMemo(
    () => costings.find(c => String(c.id) === costingId) ?? null,
    [costings, costingId],
  );

  // ── derived: assigns filtered by costing (if costing is set, prefer matches) ──
  const assignOptions = useMemo(() => {
    // pavu_assign.costing_id is not in the active load (we kept the join lean);
    // show all active assigns and let the user pick. Could filter later.
    return assigns;
  }, [assigns]);

  // ── load cost preview whenever costing changes ────────────────────────────
  useEffect(() => {
    if (!costingId) {
      setPreview(null);
      return;
    }
    (async () => {
      const { data, error: pErr } = await supabase
        .from('v_costing_two_cost')
        .select('quoted_cost_per_m, true_cost_per_m, sizing_cost_per_m, warp_cost_per_m, weft_cost_per_m')
        .eq('id', Number(costingId))
        .maybeSingle();
      if (pErr) {
        setPreview(null);
        return;
      }
      setPreview(data as unknown as CostingPreview);
    })();
  }, [supabase, costingId]);

  // ── react to pavu_assign selection: auto-fill loom + warp_lot ─────────────
  useEffect(() => {
    if (!pavuAssignId) return;
    const pa = assigns.find(x => String(x.id) === pavuAssignId);
    if (!pa) return;
    if (pa.loom?.id) setLoomId(String(pa.loom.id));
    if (pa.pavu?.sizing_job?.yarn_lot_id) {
      setWarpLotId(String(pa.pavu.sizing_job.yarn_lot_id));
    }
    if (!startDate && pa.start_date) setStartDate(pa.start_date);
  }, [pavuAssignId, assigns, startDate]);

  // ── SO line dropdown filtered to the chosen costing ───────────────────────
  const matchingSoLines = useMemo(() => {
    if (!costingId) return soLines;
    return soLines.filter(s => s.costing_id === Number(costingId));
  }, [soLines, costingId]);

  // ── submit ────────────────────────────────────────────────────────────────
  async function onSubmit(e: FormEvent): Promise<void> {
    e.preventDefault();
    setError(null);

    if (!costingId) { setError('Pick the quality being woven.'); return; }
    if (!producedM || Number(producedM) <= 0) {
      setError('Produced metres must be > 0.');
      return;
    }

    setBusy(true);

    const payload: ProductionBatchInsert = {
      // batch_code is auto-generated by trigger (migration 008)
      batch_code: '',
      costing_id: Number(costingId),
      so_line_id: soLineId ? Number(soLineId) : null,
      pavu_assign_id: pavuAssignId ? Number(pavuAssignId) : null,
      loom_id: loomId ? Number(loomId) : null,
      warp_lot_id: warpLotId ? Number(warpLotId) : null,
      weft_lot_id: weftLotId ? Number(weftLotId) : null,
      porvai_lot_id: porvaiLotId ? Number(porvaiLotId) : null,
      bobbin_1_id: bobbin1Id ? Number(bobbin1Id) : null,
      bobbin_2_id: bobbin2Id ? Number(bobbin2Id) : null,
      start_date: startDate || null,
      end_date: endDate || null,
      produced_m: Number(producedM),
      rejected_m: Number(rejectedM || 0),
      notes: notes || null,
      // Leave the actual_* columns NULL — the snapshot trigger fills them.
    };

    const { error: insErr } = await supabase.from('production_batch').insert(payload);
    setBusy(false);

    if (insErr) {
      setError(insErr.message);
      return;
    }
    router.push('/app/production');
    router.refresh();
  }

  if (loading) {
    return (
      <div>
        <PageHeader title="New Fabric Receipt" subtitle="Record a finished batch from the loom floor." />
        <div className="card p-10 text-center text-ink-soft text-sm">
          <Loader2 className="w-5 h-5 inline animate-spin mr-2" /> Loading masters…
        </div>
      </div>
    );
  }

  return (
    <div>
      <PageHeader
        title="New Fabric Receipt"
        subtitle="Record a finished batch. Cost columns are snapshotted automatically from costing + sizing_job."
        actions={
          <Link href="/app/production" className="btn-ghost">
            <ArrowLeft className="w-4 h-4" /> Back
          </Link>
        }
      />

      <form onSubmit={onSubmit} className="space-y-4 max-w-3xl">
        {/* ─── Section 1: Quality + SO line ──────────────────────────────── */}
        <section className="card p-4 space-y-3">
          <h3 className="text-sm font-semibold text-ink-soft uppercase tracking-wide">
            1. Quality being woven
          </h3>
          <div className="grid sm:grid-cols-2 gap-3">
            <div>
              <label className="label">Costing (approved) *</label>
              <select
                required
                value={costingId}
                onChange={e => setCostingId(e.target.value)}
                className="input"
              >
                <option value="" disabled>Select quality…</option>
                {costings.map(c => (
                  <option key={c.id} value={c.id}>
                    {c.quality_code} — {c.quality_name}
                  </option>
                ))}
              </select>
              {costings.length === 0 && (
                <div className="text-xs text-amber-700 mt-1">
                  No approved costings. Get one approved before recording production.
                </div>
              )}
            </div>
            <div>
              <label className="label">Against sales order (optional)</label>
              <select
                value={soLineId}
                onChange={e => setSoLineId(e.target.value)}
                className="input"
                disabled={!costingId}
              >
                <option value="">— Not linked —</option>
                {matchingSoLines.map(s => (
                  <option key={s.id} value={s.id}>
                    {s.sales_order?.so_number ?? `Line #${s.id}`} ·{' '}
                    {Number(s.delivered_m).toFixed(0)} / {Number(s.quantity_m).toFixed(0)} m
                  </option>
                ))}
              </select>
            </div>
          </div>

          {preview && (
            <div className="rounded-lg bg-cloud/60 border border-line/60 p-3 text-xs space-y-1">
              <div className="font-semibold text-ink-soft">Costing snapshot will freeze:</div>
              <div className="grid grid-cols-2 sm:grid-cols-5 gap-2 num">
                <div>Warp: <span className="font-semibold">₹{Number(preview.warp_cost_per_m ?? 0).toFixed(2)}</span></div>
                <div>Weft: <span className="font-semibold">₹{Number(preview.weft_cost_per_m ?? 0).toFixed(2)}</span></div>
                <div>Sizing: <span className="font-semibold">₹{Number(preview.sizing_cost_per_m ?? 0).toFixed(2)}</span></div>
                <div>Quoted: <span className="font-semibold">₹{Number(preview.quoted_cost_per_m ?? 0).toFixed(2)}</span></div>
                <div>True: <span className="font-semibold text-indigo">₹{Number(preview.true_cost_per_m ?? 0).toFixed(2)}</span></div>
              </div>
            </div>
          )}
        </section>

        {/* ─── Section 2: Warp (pavu_assign or manual) ───────────────────── */}
        <section className="card p-4 space-y-3">
          <h3 className="text-sm font-semibold text-ink-soft uppercase tracking-wide">
            2. Warp source
          </h3>
          <div>
            <label className="label">Pavu assignment (in-house warp)</label>
            <select
              value={pavuAssignId}
              onChange={e => setPavuAssignId(e.target.value)}
              className="input"
            >
              <option value="">— None / outsourced / manual —</option>
              {assignOptions.map(a => (
                <option key={a.id} value={a.id}>
                  {a.loom?.loom_code ?? '?'} ·{' '}
                  {a.pavu?.pavu_code ?? '?'} (Beam {a.pavu?.beam_no ?? '?'}) ·{' '}
                  Sizing {a.pavu?.sizing_job?.job_code ?? '?'}{' '}
                  · {Number(a.pavu?.meters ?? 0).toFixed(0)} m
                </option>
              ))}
            </select>
            <div className="text-xs text-ink-mute mt-1">
              Picking a pavu auto-fills the loom + warp lot and snapshots the actual sizing ₹/kg.
            </div>
          </div>
          <div className="grid sm:grid-cols-2 gap-3">
            <div>
              <label className="label">Loom</label>
              <select
                value={loomId}
                onChange={e => setLoomId(e.target.value)}
                className="input"
                disabled={!!pavuAssignId}
              >
                <option value="">— Not set —</option>
                {looms.map(l => (
                  <option key={l.id} value={l.id}>
                    {l.loom_code} ({l.status})
                  </option>
                ))}
              </select>
            </div>
            <div>
              <label className="label">Warp yarn lot</label>
              <select
                value={warpLotId}
                onChange={e => setWarpLotId(e.target.value)}
                className="input"
                disabled={!!pavuAssignId}
              >
                <option value="">— Not set —</option>
                {lots.map(l => (
                  <option key={l.id} value={l.id}>
                    {l.lot_code} · ₹{Number(l.cost_per_kg).toFixed(2)}/kg ·{' '}
                    {Number(l.current_kg).toFixed(1)} kg avail
                  </option>
                ))}
              </select>
            </div>
          </div>
        </section>

        {/* ─── Section 3: Weft + Porvai ──────────────────────────────────── */}
        <section className="card p-4 space-y-3">
          <h3 className="text-sm font-semibold text-ink-soft uppercase tracking-wide">
            3. Weft + Porvai
          </h3>
          <div className="grid sm:grid-cols-2 gap-3">
            <div>
              <label className="label">Weft yarn lot</label>
              <select
                value={weftLotId}
                onChange={e => setWeftLotId(e.target.value)}
                className="input"
              >
                <option value="">— Not set —</option>
                {lots.map(l => (
                  <option key={l.id} value={l.id}>
                    {l.lot_code} · ₹{Number(l.cost_per_kg).toFixed(2)}/kg
                  </option>
                ))}
              </select>
            </div>
            <div>
              <label className="label">
                Porvai yarn lot {chosenCosting?.use_porvai === false && (
                  <span className="text-ink-mute text-xs">(not used in this quality)</span>
                )}
              </label>
              <select
                value={porvaiLotId}
                onChange={e => setPorvaiLotId(e.target.value)}
                className="input"
                disabled={chosenCosting?.use_porvai === false}
              >
                <option value="">— Not set —</option>
                {lots.map(l => (
                  <option key={l.id} value={l.id}>
                    {l.lot_code} · ₹{Number(l.cost_per_kg).toFixed(2)}/kg
                  </option>
                ))}
              </select>
            </div>
          </div>
        </section>

        {/* ─── Section 4: Bobbins ────────────────────────────────────────── */}
        <section className="card p-4 space-y-3">
          <h3 className="text-sm font-semibold text-ink-soft uppercase tracking-wide">
            4. Bobbins
          </h3>
          <div className="grid sm:grid-cols-2 gap-3">
            <div>
              <label className="label">
                Bobbin 1 {chosenCosting?.use_bobbin_1 === false && (
                  <span className="text-ink-mute text-xs">(not used)</span>
                )}
              </label>
              <select
                value={bobbin1Id}
                onChange={e => setBobbin1Id(e.target.value)}
                className="input"
                disabled={chosenCosting?.use_bobbin_1 === false}
              >
                <option value="">— Not set —</option>
                {bobbins.map(b => (
                  <option key={b.id} value={b.id}>
                    {b.code} — {b.description}{b.is_lurex ? ' (lurex)' : ''}
                  </option>
                ))}
              </select>
            </div>
            <div>
              <label className="label">
                Bobbin 2 {chosenCosting?.use_bobbin_2 === false && (
                  <span className="text-ink-mute text-xs">(not used)</span>
                )}
              </label>
              <select
                value={bobbin2Id}
                onChange={e => setBobbin2Id(e.target.value)}
                className="input"
                disabled={chosenCosting?.use_bobbin_2 === false}
              >
                <option value="">— Not set —</option>
                {bobbins.map(b => (
                  <option key={b.id} value={b.id}>
                    {b.code} — {b.description}{b.is_lurex ? ' (lurex)' : ''}
                  </option>
                ))}
              </select>
            </div>
          </div>
        </section>

        {/* ─── Section 5: Production data ────────────────────────────────── */}
        <section className="card p-4 space-y-3">
          <h3 className="text-sm font-semibold text-ink-soft uppercase tracking-wide">
            5. Production
          </h3>
          <div className="grid sm:grid-cols-2 gap-3">
            <div>
              <label className="label">Start date</label>
              <input
                type="date"
                value={startDate}
                onChange={e => setStartDate(e.target.value)}
                className="input"
              />
            </div>
            <div>
              <label className="label">End date</label>
              <input
                type="date"
                value={endDate}
                onChange={e => setEndDate(e.target.value)}
                className="input"
              />
            </div>
            <div>
              <label className="label">Produced (m) *</label>
              <input
                type="number"
                min="0"
                step="0.01"
                required
                value={producedM}
                onChange={e => setProducedM(e.target.value)}
                className="input num"
              />
            </div>
            <div>
              <label className="label">Rejected (m)</label>
              <input
                type="number"
                min="0"
                step="0.01"
                value={rejectedM}
                onChange={e => setRejectedM(e.target.value)}
                className="input num"
              />
            </div>
          </div>
          <div>
            <label className="label">Notes</label>
            <textarea
              value={notes}
              onChange={e => setNotes(e.target.value)}
              rows={2}
              className="input"
              placeholder="Anything the floor or accounts should know about this batch."
            />
          </div>
        </section>

        {error && (
          <div className="card p-3 text-sm text-err bg-red-50/40 border-red-100">{error}</div>
        )}

        <div className="flex items-center justify-end gap-2">
          <Link href="/app/production" className="btn-ghost">Cancel</Link>
          <button type="submit" className="btn-primary" disabled={busy || !costingId || !producedM}>
            {busy ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" /> Saving…
              </>
            ) : (
              'Record receipt'
            )}
          </button>
        </div>
      </form>
    </div>
  );
}
