/**
 * iOS splash-screen (Add-to-Home-Screen launch image) generator.
 *
 * Android/Chrome build their PWA splash automatically from manifest.json
 * (icon + name + background_color). iOS does NOT — it needs a pre-rendered
 * PNG per device resolution, referenced via:
 *   <link rel="apple-touch-startup-image" media="..." href="..." />
 * Without these, iOS shows a blank white screen while the app boots.
 *
 * This script renders the brand splash (PT mark + "PPK TEX" on the navy brand
 * colour) into every common iPhone/iPad portrait size, and emits the matching
 * <link> tags as a React component.
 *
 * Run from the app directory:
 *     npm install --save-dev sharp
 *     node scripts/generate-splash.mjs
 *
 * Commit the generated PNGs + component once — they don't regenerate on build.
 */
import sharp from 'sharp';
import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __filename = fileURLToPath(import.meta.url);
const APP_DIR = join(dirname(__filename), '..');
const PUBLIC_DIR = join(APP_DIR, 'public');
const SPLASH_DIR = join(PUBLIC_DIR, 'splash');
const COMPONENT_PATH = join(APP_DIR, 'app', 'components', 'apple-splash-links.tsx');

const NAVY = '#1F2057';
const TILE = '#23265f';
const GOLD = '#E8B040';
const WHITE = '#ffffff';

// Common iOS devices as CSS dimensions + device-pixel-ratio (portrait).
const DEVICES = [
  { w: 320, h: 568, dpr: 2 },
  { w: 375, h: 667, dpr: 2 },
  { w: 375, h: 812, dpr: 3 },
  { w: 390, h: 844, dpr: 3 },
  { w: 393, h: 852, dpr: 3 },
  { w: 414, h: 736, dpr: 3 },
  { w: 414, h: 896, dpr: 2 },
  { w: 414, h: 896, dpr: 3 },
  { w: 428, h: 926, dpr: 3 },
  { w: 430, h: 932, dpr: 3 },
  { w: 768, h: 1024, dpr: 2 },
  { w: 810, h: 1080, dpr: 2 },
  { w: 820, h: 1180, dpr: 2 },
  { w: 834, h: 1112, dpr: 2 },
  { w: 834, h: 1194, dpr: 2 },
  { w: 1024, h: 1366, dpr: 2 },
];

/** The brand mark, drawn inside a 0..110 viewBox (tile + woven PT monogram). */
function markInner() {
  return `
    <rect x="6" y="6" width="98" height="98" rx="16" fill="${TILE}" stroke="${GOLD}" stroke-width="2"/>
    <g stroke="${GOLD}" stroke-width="2" opacity="0.30">
      <line x1="20" y1="14" x2="20" y2="96"/>
      <line x1="32" y1="14" x2="32" y2="96"/>
      <line x1="80" y1="14" x2="80" y2="96"/>
      <line x1="90" y1="14" x2="90" y2="96"/>
    </g>
    <path d="M 28 30 L 28 84 M 28 30 L 52 30 Q 70 30 70 44 Q 70 58 52 58 L 28 58"
          stroke="${WHITE}" stroke-width="9" fill="none" stroke-linecap="square" stroke-linejoin="miter"/>
    <path d="M 42 44 L 84 44 M 64 44 L 64 86"
          stroke="${GOLD}" stroke-width="9" fill="none" stroke-linecap="square"/>`;
}

/** Compose a full splash SVG for the given pixel canvas. */
function splashSvg(pw, ph) {
  const cx = pw / 2;
  const S = Math.round(Math.min(pw, ph) * 0.26);
  const nameSize = Math.round(S * 0.22);
  const gapMarkName = Math.round(S * 0.24);
  const blockH = S + gapMarkName + nameSize;
  const top = Math.round((ph - blockH) / 2);
  const markX = Math.round(cx - S / 2);
  const nameBaseline = top + S + gapMarkName + nameSize;

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${pw}" height="${ph}" viewBox="0 0 ${pw} ${ph}">
    <rect width="${pw}" height="${ph}" fill="${NAVY}"/>
    <svg x="${markX}" y="${top}" width="${S}" height="${S}" viewBox="0 0 110 110">${markInner()}</svg>
    <text x="${cx}" y="${nameBaseline}" text-anchor="middle"
          font-family="Georgia, 'Times New Roman', serif" font-weight="700"
          font-size="${nameSize}" letter-spacing="${(nameSize * 0.08).toFixed(1)}"
          fill="${WHITE}">PPK TEX</text>
  </svg>`;
}

await mkdir(SPLASH_DIR, { recursive: true });

const links = [];
for (const { w, h, dpr } of DEVICES) {
  const pw = w * dpr;
  const ph = h * dpr;
  const file = `splash-${pw}x${ph}.png`;
  const png = await sharp(Buffer.from(splashSvg(pw, ph))).png().toBuffer();
  await writeFile(join(SPLASH_DIR, file), png);
  // eslint-disable-next-line no-console
  console.log(`Wrote ${file} (${png.length} bytes)`);
  const media =
    `screen and (device-width: ${w}px) and (device-height: ${h}px) ` +
    `and (-webkit-device-pixel-ratio: ${dpr}) and (orientation: portrait)`;
  links.push(`      <link rel="apple-touch-startup-image" media="${media}" href="/splash/${file}" />`);
}

const component = `// AUTO-GENERATED by scripts/generate-splash.mjs — do not edit by hand.
// iOS launch (splash) images for the installed PWA. Rendered into <head> by
// Next.js when this component is included in the root layout tree.
export function AppleSplashLinks(): React.ReactElement {
  return (
    <>
${links.join('\n')}
    </>
  );
}
`;

await writeFile(COMPONENT_PATH, component);
// eslint-disable-next-line no-console
console.log(`\nWrote component ${COMPONENT_PATH}`);
// eslint-disable-next-line no-console
console.log('Done. Include <AppleSplashLinks /> in app/app/layout.tsx.');
